### ISSUE TITLE
Crash EXC_BAD_ACCESS saving .ccb

### ISSUE THREAD

**Issue by frisoft** [cocos2d/CocosBuilder#10]
In master and develop branch.

When I save a CCB,
EXC_BAD_ACCESS in line 726 of CocosBuilderAppDelegate.m:
NSArray\* activeDirs = [NSMutableArray arrayWithObject:document.rootPath];

On OSX Lion 10.7

**Comment by ghost** [comment]
I'm seeing this a lot too.

**Comment by ghost** [comment]
Im also getting EXC_BAD_ACCESS on line 843 for saving files

[[NSDocumentController sharedDocumentController] noteNewRecentDocumentURL:[NSURL fileURLWithPath:fileName]];

(OSX Lion)

**Comment by nolsen** [comment]
Looks like one problem is that there needs to be a getter set for CCBDocument's rootPath property, for example, change CCBDocument line 53 from 

@property (nonatomic,readonly) NSString\* rootPath;

to

@property (nonatomic,readonly, getter = rootPath) NSString\* rootPath;

Although with that fixed there is another crash, which I'm looking at.

**Comment by nolsen** [comment]
Also looks like in CCBDocument.m, setFileName, when saving the new file name and old file name point to the same NSString object, so when the old filename is released, it deallocates the string object which then gets assigned as the new filename which is now reclaimed memory.

This can be fixed by changing these lines

```
[fileName release];
fileName = [fn retain];
```

To

```
// Set new filename
NSString* oldFileName = fileName;
fileName = [fn retain];
[oldFileName release];
```

With the above two changes saving does not crash, even saving multiple times doesn't crash.

**Comment by vlidholt** [comment]
Thanks for your comments, I will look into this issue!

**Comment by vlidholt** [comment]
@nolsen I have implemented your second fix, and will push it to the development branch, hopefully, tomorrow (need to get a couple of things merged into cocos2d for my other updates to work first). For the first fix, the getter is set implicitly, so I don't see how you fix would do anything differently, or am I missing something obvious?

**Comment by nolsen** [comment]
It's a subtle naming issue, to work implicitly the accessor needs to be getRootPath, so another option to fix it would be to rename the method rootPath to getRootPath. I set the getter explicitly in case there was other code calling rootPath, but you can decide what's best.

**Comment by vlidholt** [comment]
This has most likely been fixed (master branch) can you confirm?

**Comment by nolsen** [comment]
I'm actually going out of town for two weeks starting tomorrow. I was
hoping to have another look at this stuff and package up my MenuItemFont
support but I'll have to get to it when I get back or if I have some down
time while I'm gone.

Good luck, it was fun getting started with your project and I plan to keep
at it.

Nick

On Wed, Mar 28, 2012 at 10:03 AM, Viktor Lidholt <
reply@reply.github.com

**Comment by frisoft** [comment]
I confirm, now it works!

Thank you.

Andrea

**Comment by vlidholt** [comment]
Thanks! :)
