### ISSUE TITLE
Custom Class/Custom Properties (V2.1 Beta2)

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#101]
When removing a Custom Class, the Custom Properties are left. After publishing, your application will ASSERT due to the custom properties.

I believe keeping the properties in CocosBuilder to be a great idea (removing class to test something, etc). Would it be possible to exclude the custom properties when publishing the CCBI files if no class is set?

**Comment by vlidholt** [comment]
Fixed!
