### ISSUE TITLE
Enable/Disable - In Animations (V2.1 Beta2)

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#102]
The Enable/Disable option for CCControlButton appears to be "global" and not per animation. Is this possible?

Reason: We have a 15second intro animation and would like to disable the menu while it slides, fades, etc in....

If not, what is the best approach?

EDIT: Even using two timelines shares the Enabled status.

**Comment by vlidholt** [comment]
The enabled property is not animatable. You can use multiple timelines and use the callbacks to change non-animatable properties at specific times.

**Comment by Tw0bit** [comment]
Hi Viktor,

Thanks for the reply, I will use your suggest solution.

That logic definaty aligns with the cocosbuilder timeline features.

Regards
Tw0bit
