### ISSUE TITLE
Crash when publishing scene made by CocosBuilder 1.0[V2.1 Beta 2]

### ISSUE THREAD

**Issue by huangyuching** [cocos2d/CocosBuilder#103]
The ccb files created by CocosBuilder 1.0 can be opened in CocosBuilder 2.0, but the application will crash when publishing. By the way, when you switch to other tab then come back, the layout is messed up.

**Comment by vlidholt** [comment]
You will need to update the ccb-files before you can export them. To this by opening them and saving them. (There is a menu option for updating a complete directory, File > Update Files in Directory...)
