### ISSUE TITLE
CCB file of type ccSprite/ccLayer with Animations [CB 2.1 Beta2]

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#105]
In CocosBuilder, I am able to animate CCB Files of type CCSprite and CCLayer however the animations do not play when complied in xCode.

(i.e. if we had the demo header slide from the bottom to the top), however the child animations in the CCLayer do play (wriggling the back button).

Is this the expected behavior?

**Comment by Tw0bit** [comment]
It appears that even the visible animation is ignored in xCode. I have been trying to use a CCSprite to animate the CCB-CCSprite "entry" and then hide the CCSprite and unhide the CCB-Sprite >> Sadly that idea did not work out either...

**Comment by vlidholt** [comment]
This has been fixed on the latest version on master branch

**Comment by Tw0bit** [comment]
Hi Victor,

Great to hear! Thank you for all your work on CocosBuilder.
