### ISSUE TITLE
V1 ccb-files updated in CocosBuilder 2.1 Beta 2 lose position property of all its objects.  

### ISSUE THREAD

**Issue by huangyuching** [cocos2d/CocosBuilder#109]
It seems every thing fine when updating V1 ccb-file in CocosBuilder 2.1 Beta 2. But if you close the file and reopen it, you will see the layout is messed up and every object seems to be located at (0,0). Open this file in any text editor, you can see the position property of every object is gone.

**Comment by vlidholt** [comment]
Fixed
