### ISSUE TITLE
After saving and loading a scene with a BMFont label, label cannot be selected

### ISSUE THREAD

**Issue by nolsen** [cocos2d/CocosBuilder#11]
This must have something to do with using the default' missing-font instead of setting a font explicitly. Anyway, eventually we end up in TexturePropertySetter::fontForNode and if the function were to return @"missing-font.fnt" instead of NULL, the label would at least be selectable and rendered with the default font.

**Comment by vlidholt** [comment]
I think that this bug is now fixed (master branch) can you confirm?

**Comment by vlidholt** [comment]
Probably fixed :)
