### ISSUE TITLE
AnimationManager - Allocating userObject in initial scene (appdelegate)

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#110]
Question: How does the userObject get defined by CCBReader? I am trying to run an animation in the initial scene loaded by the AppDelegate. Is this possible?

Initial Scene loaded by AppDelegate:
I am loading my menu screen in the AppDelegate with this code: [director runWithScene: [CCBReader sceneWithNodeGraphFromFile:@"sceneMenu.ccbi"]], I have also tried: [director runWithScene: [CCBReader sceneWithNodeGraphFromFile:@"sceneMenu.ccbi"] owner:self];

However, this line in the didLoadFromCCB ( self.animationManager = self.userObject; )  does not get a value/is NULL. self.userObject is also nul.

From Menu Scene/Sub Classes:
The AnimationManger works if the scene is loaded from the Menu ( [CCBReader sceneWithNodeGraphFromFile:ccbFile owner:self] ) or used in a custom sub-class for a CCSprite.

The two lines appear to be identical, so I would imagine it should work? The code for both the Menu and "Levels" are copied from the CocosBuilderExample.

**Comment by Tw0bit** [comment]
Issue resolved - was with custom code.

**Comment by plungeint** [comment]
can you share your code? this is an open source project...
