### ISSUE TITLE
CCScrollView minor memory issue

### ISSUE THREAD

**Issue by himanshugupta53** [cocos2d/CocosBuilder#113]
If setContainer is called to set the container of a scrollview, the previous container doesn't get released and remains in the memory. Put a [container_ release] in the setContainer: function to fix it.

**Comment by vlidholt** [comment]
container_ is not retained by the setContainer: method directly. It is retained by the addChild: method and released by calling removeAllChildrenWithCleanUp:

Found and fixed another small bug though. The container can now be set to NULL.

**Comment by himanshugupta53** [comment]
The property container is defined as @property (nonatomic, retain) CCNode\* container;
Which means there is an extra retain hanging. Also memory profiling has been done and we see that the container remains in the memory even after the scrollview deallocates if setContainer is used to set the container.
