### ISSUE TITLE
[2.1rc0] CCSprite - Unable to set Image/Sprite Frame

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#116]
In 2.1b2 we were able to edit the following THREE animations for CCSprites: Sprite Frame, Opacity and Color. These have been removed in 2.1rc0 - is that "Animatable properties are now disabled for root nodes and ccb sub files"?

In addition, we are now unable to select the Sprite Frame/Image for the CCSprite ccbfile from the default value "texture missing" when creating a new CCSprite ccb or editing an existing CCSprite ccb.

**Comment by vlidholt** [comment]
I messed up the enabling/disabling of properties for root nodes. I think it should work correctly now!

**Comment by Tw0bit** [comment]
I can confirm it is working as per 2.1b2.
