### ISSUE TITLE
[2.1rc0] Custom Properties (setting for CCSprite CCBfiles)

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#117]
I have several CCB sprites with custom properties. For example, a sprite has a string Custom Property for "Name".

When published in 2.1rc0 the sprites always get the default value (name) set in the CCB CCSprite file.

When published in 2.1b2 the sprites are correctly given the value set in the level CCB file (fred, harry, george, etc).

**Comment by vlidholt** [comment]
I think I've fixed it now. At least it seems to work for the CocosDragon tutorial project

**Comment by Tw0bit** [comment]
I can confirm it is working as per 2.1b2.

**Comment by stevekanter** [comment]
I'm using 2.1b2 and the issue, remains for me.  I'm using a Bool - would that make any difference?
