### ISSUE TITLE
Reverse Animation Feature

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#122]
Hi Vik,

Is the Reverse Animation feature which was mentioned as planned ( http://www.cocos2d-iphone.org/forum/topic/32775 ) going to make in to CocosBuilder in the 2.x series or more likely 3.x?

Just busy animating some intro/exit scenes - would be great to call the intro scene in reverse :-).

**Comment by vlidholt** [comment]
This feature is implemented. You can select a number of keyframes and choose "Reverse selected keyframes" from the Animation menu.

**Comment by AlexanderBykin** [comment]
Can you please implement method in Animation manager to run animation reverse ?
