### ISSUE TITLE
Animations on different timelines can't run at the same time

### ISSUE THREAD

**Issue by therealhugocosta** [cocos2d/CocosBuilder#123]
Animations on different timelines can't run at the same time.

Example:
1. Create two timelines for two sprites and do some animations for each.
2. In code detect touches for both the sprites and trigger the corresponding animations to run.

Run the app:
1. Touch the first sprite. The animation for sprite 1 starts.
2. Touch the second sprite. The animation for sprite 1 is interrupted, and the animation for sprite 2 begins.

**Comment by vlidholt** [comment]
This is the intended behavior. The timeline is for all objects in your ccb-file. If you want different animations for the different sprites you can have sub ccb-files in your project.

**Comment by plungeint** [comment]
I don't understand why we cannot execute multiple timelines on the same CCB, that would be cool.
