### ISSUE TITLE
Sprites with the same name on different scenes

### ISSUE THREAD

**Issue by therealhugocosta** [cocos2d/CocosBuilder#124]
CocosBuilder will get confused and show the wrong sprite if it's used different sprites with the same name in different scenes (different ccb files). In the same project.

Example:

Two ccb Scenes with different background.png files, will show sometimes the wrong background on the wrong scene when editing.

Solution:

Making sure that you have background-scene1.png and background-scene2.png. :)

**Comment by vlidholt** [comment]
Not a bug. CocosBuilder uses a global name space for all resources, no matter in what resource path they are in. If you want to use similarly named files, place them in sub directories and uncheck the "Flatten resource paths" option in the project settings.
