### ISSUE TITLE
CCLayerColor + CCLayerGradient doesn't work

### ISSUE THREAD

**Issue by robgraeber** [cocos2d/CocosBuilder#129]
At least for me CCLayerColor + CCLayerGradient stopped working since 2.1. I'm using the 2.1 RC 1 build and it shows up in CocosBuilder but not in the compiled app. It worked fine in 2.0, and it old ccb files compile fine if I don't resave them using 2.1. But when I resave the 2.0 ccb files using 2.1, they stop working.

**Comment by Tw0bit** [comment]
We have a CCLayer which holds our animated sky (some animated sprites etc). In this layer we have a CCLayerGradient with different blues.

This is then added as a CCBFile to our Background Layer (animated "earthy" items: trees etc) and finally added to another CCLayer for the lesson. (i.e. three layers down). 

We have not had any issues with 2.1b1 to 2.1rc1.

**Comment by robgraeber** [comment]
Does that mean it's working for you?

**Comment by Tw0bit** [comment]
No issues for us with CCLayerGradient with 2.1b1 to 2.1rc1 - at least in our application.

Have you tried the CocosBuilderExample files which includes a gradient background for some scenes? In particular: TestParticleSystems.ccb.

**Comment by robgraeber** [comment]
Hmm you're right, turns out it was on my end. I re-downloaded the latest cocos2d version and it works now, I must have somehow edited the source and broke them.

**Comment by alex-chan** [comment]
You are right!  cocosbuilder v2.1-rc3 does work on cocos-iphone 2.0.0 , but works well on cocos-iphone 2.1 beta2

**Comment by emmychen** [comment]
I have the latest cocos2d-iphone and cocosbuilder, the cclayergradient does not work.

**Comment by haysclark** [comment]
+1 for having no gradients. :(  I have Cocos2D 2.0.0 I think and CocosBuilder-2.1.  I grabbed the CCBReader from the 
"Add to Your Project/cocos2d-iphone" folder.

**Comment by MadPig** [comment]
To fix, download and use http://cocos2d-iphone.googlecode.com/files/cocos2d-iphone-2.1-beta4.tar.gz

**Comment by vlidholt** [comment]
This should have been fixed in later versions of CCB.
