### ISSUE TITLE
CocosBuilder 2.1 beta Save the file before publish

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos2d/CocosBuilder#130]
Hello,

It will be great if the CocosBuilder can save the file before publishing the ccbi file.

Because CocosBuilder 2.1 beta publishes the file from the last saved file.

Thanks.

Great tool!

**Comment by Tw0bit** [comment]
@babben - I recently added the request as #114 which has been marked as an Enhancement :-).

I spent several hours the first day working out what was wrong until realised it does not auto save.

**Comment by BenoitFreslon** [comment]
Great!

I didn't know how to put the label enhancement.

I spent several hours the first day working out what was wrong until realised it does not auto save.

Me too :).
