### ISSUE TITLE
plugin node does not show properties

### ISSUE THREAD

**Issue by dillon-courts** [cocos2d/CocosBuilder#131]
I am having issues with plugins for the newest version of CocosBuilder, 2.1 RC. I compile the example plugin (CCRotatingSprite plugin) and place the "CCRotatingSprite.ccPlugNode" folder inside the "plugIns" directory of the CocosBuilder application. I then run CocosBuilder and create a new project. I then add a CCRotatingSprite node to the HelloCocosBuilder.ccb file. I can see the sprite rotating on screen however no properties display in the right hand side bar when it is highlighted. However, properties do display for other nodes such as CCLabelTTF and CCLayer. When I follow the same process with CocosBuilder version 2.0, the CCRotatingSprite displays its properties correctly.
2.0 CCRotatingSprite Selected http://i.imgur.com/V8g7o.jpg
2.1 LabelTTF selected http://i.imgur.com/y0UF9.jpg
2.1 CCRotatingSprite Selected http://i.imgur.com/8WiN9.jpg

**Comment by vlidholt** [comment]
Fixed

**Comment by zcom2012** [comment]
I encountered the same problem with you, I ask you how to solve this problem    Version：3.0

**Comment by alexgames** [comment]
I have the same problem
please fix it
thanks
v 3.0

**Comment by alexgames** [comment]
hey, i got it
in 3.0 you should set for Separator property
name = CCRotatingSprite;
dontSetInEditor = YES;

**Comment by ryanflees** [comment]
I started to learn how to add custom node as plugins in CocosBuilder, and i have this same problem as well both in v3.04 and v3.05.
And added name = XXXX to the Separator dictionary of properties array, the property panel in CCB can be shown properly now.
