### ISSUE TITLE
Get the CCNode (graphnode) when CCBReader load a scene #enhancement

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos2d/CocosBuilder#132]
Hello,

It will be great if we could get the CCNode (the node graph) when CCBReader load a scene like:

[CCBReader sceneWithNodeGraphFromFile:@"test_layer.ccbi" owner:self]

I actually add a simple line in order to set a tag on the CCNode when the node is loaded.

```
+ (CCScene*) sceneWithNodeGraphFromFile:(NSString *)file owner:(id)owner parentSize:(CGSize)parentSize
{
    CCNode* node = [CCBReader nodeGraphFromFile:file owner:owner parentSize:parentSize];
    node.tag = 1
    CCScene* scene = [CCScene node];
    [scene addChild:node];
    return scene;
}
```

Then I load the ccbi file like this and I can get the nodegraph.

```
CCScene *scene = [CCBReader sceneWithNodeGraphFromFile:@"test_layer.ccbi" owner:self];
CCLOG(@"nodegraph %@", [scene getChildByTag:1] );
```

Now I can call methods on the nodegraph

Here TestLayer is the Class of the CCLayer on the CocosBuilder.

```
[(TestLayer *)node testMethod];
```

Thanks.

PS: I don't know how to put tags in github. Can you tell me how? Thanks.

**Comment by vlidholt** [comment]
1. You can already set the tag inside CocosBuilder
2. If you need direct access to the node graph, use the nodeGraphFromFile: method of CCBReader
