### ISSUE TITLE
Can't set visible to false on CCMenuItem on CocosBuilder 2.1 beta

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos2d/CocosBuilder#133]
Hello,

When I uncheck the checkbox "visible" > Save the file > Export the file.

Then I click everywhere on the interface the CCMenuItem back to visible.

**Comment by kagakuninja** [comment]
I see the same thing happen with any object.  Create a new file, add a CCNode, uncheck the "visible" checkbox.  Publish.  The object will be visible again.  I am using 2.1 RC1

**Comment by vlidholt** [comment]
Fixed (on develop branch)

**Comment by Tw0bit** [comment]
@vlidholt : I grabbed RC2 which lists this as being fixed (change log)... I am unable to set the visible flags for CCNodes (CCLayers with CCNodes holding CCSprites - for animations).. Do I need to build the git release?
