### ISSUE TITLE
Root nodes never get released (Version 2.1 RC 3)

### ISSUE THREAD

**Issue by lit35oftware** [cocos2d/CocosBuilder#138]
Version 2.1 RC 3

Steps to reproduce:

1) Open CocosBuilderExample.xcodeproj in Xcode.

2) Profile for leaks (Product --> Profile -->  Leaks).

3) On the app, move between different tests (e.g. "Menus & Items", "Sprites & 9 Slice", etc.) and eventually the app will crash. 

The leaks profiler doesn't show any leaks, but the "Live Bytes" column confirms that more and more allocations are made when transitioning between different tests.  In other words, the root nodes are never being released (dealloc-ed).  This is what causes the crash.

**Comment by Tw0bit** [comment]
@lit35oftware I also noticed that not all of our CCB loaded files were getting deallocated (the Leaks profiler showed no errors). We also checked the Example application and found that the deallocs were not getting called (added NSLog, CCLog and Break-points).

Our sub CCB's did dealloc correctly but never the Root Node (we are using replaceScene). In an attempt to ensure it was not our programming, we moved to ARC for our code (Cocos2d as a sub-project and CCB files excluded from ARC). Our deallocs are not called but the onExit does an cocos2d lists alot of deallocs.

Our profiler still shows the Live Bytes increasing as we swap between the lessons etc. We have not yet crashed the Example or our App (yet?).

**Comment by vlidholt** [comment]
I've been going through the CCBReader source code, and cannot see why this happens. Anyone got some idea of how to go about to find the leak?

**Comment by windowrunner** [comment]
I found it using XCode's profiler. My scene's root nodes were all CCLayers and I noticed the Living count was never going down after scene changes. I clicked on CCLayer, then clicked on it's address. This showed me all the retains & releases. Here I saw that CCBAnimationManager was retaining via setRootNode but never releasing.
I changed the CCBAnimationManager.rootNode property from retain to assign and that fixed my leak.

**Comment by vlidholt** [comment]
Thank you! I think that this should be a valid solution for the memory leak. I will fix it and release a new version of CocosBuilder 2.1 and CCBReader!

**Comment by Silnar** [comment]
Same applies to delegate property which also should be declared with 'assign' instead of 'retain'.

Also nodeSequences and baseValues keys shouldn't be retained, because of sprite->animationMgr->nodeSequences/baseValues->sprite circular-references.

**Comment by vlidholt** [comment]
This has been fixed.
