### ISSUE TITLE
Saves corrupted since 1.1 beta

### ISSUE THREAD

**Issue by adamlwgriffiths** [cocos2d/CocosBuilder#14]
Was using the 1.1 dmg on the blog. Had it corrupt my work a few times.
Built from Git head (checked out clean today), same issue occurs.
Loading the file then fails.

Console output from session is as follows:

2012-03-28 21:25:20.861 CocosBuilder[2465:703] Could not find image named 'menu-pro'.
2012-03-28 21:25:21.015 CocosBuilder[2465:703] cocos2d: cocos2d v2.0.0-rc0-post
2012-03-28 21:25:21.016 CocosBuilder[2465:703] cocos2d: Using Director Type:CCDirectorDisplayLink
2012-03-28 21:25:21.124 CocosBuilder[2465:703] cocos2d: OS version: 10.7.3 (0x0a070300)
2012-03-28 21:25:21.124 CocosBuilder[2465:703] cocos2d: GL_VENDOR:   ATI Technologies Inc.
2012-03-28 21:25:21.137 CocosBuilder[2465:703] cocos2d: GL_RENDERER: AMD Radeon HD 6970M OpenGL Engine
2012-03-28 21:25:21.137 CocosBuilder[2465:703] cocos2d: GL_VERSION:  2.1 ATI-7.18.11
2012-03-28 21:25:21.138 CocosBuilder[2465:703] cocos2d: GL_MAX_TEXTURE_SIZE: 16384
2012-03-28 21:25:21.138 CocosBuilder[2465:703] cocos2d: GL_MAX_TEXTURE_UNITS: 16
2012-03-28 21:25:21.139 CocosBuilder[2465:703] cocos2d: GL_MAX_SAMPLES: 8
2012-03-28 21:25:21.139 CocosBuilder[2465:703] cocos2d: GL supports PVRTC: NO
2012-03-28 21:25:21.139 CocosBuilder[2465:703] cocos2d: GL supports BGRA8888 textures: YES
2012-03-28 21:25:21.140 CocosBuilder[2465:703] cocos2d: GL supports NPOT textures: YES
2012-03-28 21:25:21.140 CocosBuilder[2465:703] cocos2d: GL supports discard_framebuffer: NO
2012-03-28 21:25:21.141 CocosBuilder[2465:703] cocos2d: compiled with Profiling Support: NO
2012-03-28 21:25:21.220 CocosBuilder[2465:703] cocos2d: startAnimation
2012-03-28 21:25:21.300 CocosBuilder[2465:703] Loading PlugIn: CCBFile.ccbPlugNode
2012-03-28 21:25:21.306 CocosBuilder[2465:703] Loading PlugIn: CCLabelBMFont.ccbPlugNode
2012-03-28 21:25:21.307 CocosBuilder[2465:703] Loading PlugIn: CCLabelTTF.ccbPlugNode
2012-03-28 21:25:21.308 CocosBuilder[2465:703] Loading PlugIn: CCLayer.ccbPlugNode
2012-03-28 21:25:21.309 CocosBuilder[2465:703] Loading PlugIn: CCLayerColor.ccbPlugNode
2012-03-28 21:25:21.311 CocosBuilder[2465:703] Loading PlugIn: CCLayerGradient.ccbPlugNode
2012-03-28 21:25:21.312 CocosBuilder[2465:703] Loading PlugIn: CCMenu.ccbPlugNode
2012-03-28 21:25:21.316 CocosBuilder[2465:703] Loading PlugIn: CCMenuItemImage.ccbPlugNode
2012-03-28 21:25:21.318 CocosBuilder[2465:703] Loading PlugIn: CCNode.ccbPlugNode
2012-03-28 21:25:21.319 CocosBuilder[2465:703] Loading PlugIn: CCParticleSystem.ccbPlugNode
2012-03-28 21:25:21.323 CocosBuilder[2465:703] Loading PlugIn: CCSprite.ccbPlugNode
2012-03-28 21:25:21.325 CocosBuilder[2465:703] Loading PlugIn: Cocos2D iPhone.ccbPlugExport
2012-03-28 21:25:28.257 CocosBuilder[2465:703] cocos2d: CCTexture2D: Using RGBA888 texture since image has no alpha
2012-03-28 21:25:28.303 CocosBuilder[2465:703] An uncaught exception was raised
2012-03-28 21:25:28.303 CocosBuilder[2465:703] **\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
2012-03-28 21:25:28.306 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83a6d582 -[__NSArrayM objectAtIndex:] + 274
    3   CocosBuilder                        0x000000010004bcaf +[CCBReaderInternal setProp:ofType:toValue:forNode:] + 4831
    4   CocosBuilder                        0x000000010004c163 +[CCBReaderInternal nodeGraphFromDictionary:] + 675
    5   CocosBuilder                        0x000000010004c371 +[CCBReaderInternal nodeGraphFromDictionary:] + 1201
    6   CocosBuilder                        0x000000010004c371 +[CCBReaderInternal nodeGraphFromDictionary:] + 1201
    7   CocosBuilder                        0x000000010004c371 +[CCBReaderInternal nodeGraphFromDictionary:] + 1201
    8   CocosBuilder                        0x000000010004c5bf +[CCBReaderInternal nodeGraphFromDocumentDictionary:] + 495
    9   CocosBuilder                        0x000000010000527f -[CocosBuilderAppDelegate replaceDocumentData:] + 47
    10  CocosBuilder                        0x0000000100005650 -[CocosBuilderAppDelegate switchToDocument:forceReload:] + 544
    11  CocosBuilder                        0x0000000100005773 -[CocosBuilderAppDelegate switchToDocument:] + 67
    12  CocosBuilder                        0x00000001000060ab -[CocosBuilderAppDelegate openFile:] + 1371
    13  CocosBuilder                        0x0000000100006834 -[CocosBuilderAppDelegate application:openFile:] + 52
    14  AppKit                              0x00007fff8d16aea5 -[NSDocumentController%28NSPrivate%29 _openRecentDocument:] + 270
    15  CoreFoundation                      0x00007fff83acf75d -[NSObject performSelector:withObject:] + 61
    16  AppKit                              0x00007fff8ce9fcb2 -[NSApplication sendAction:to:from:] + 139
    17  AppKit                              0x00007fff8cf8cfe7 -[NSMenuItem _corePerformAction] + 399
    18  AppKit                              0x00007fff8cf8cd1e -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 125
    19  AppKit                              0x00007fff8d22add4 -[NSMenu _internalPerformActionForItemAtIndex:] + 38
    20  AppKit                              0x00007fff8d0bb3a9 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 138
    21  AppKit                              0x00007fff8cf06b4b NSSLMMenuEventHandler + 339
    22  HIToolbox                           0x00007fff8363e294 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1263
    23  HIToolbox                           0x00007fff8363d8a0 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 446
    24  HIToolbox                           0x00007fff83654677 SendEventToEventTarget + 76
    25  HIToolbox                           0x00007fff8369a6c1 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 398
    26  HIToolbox                           0x00007fff83781c59 SendMenuCommandWithContextAndModifiers + 56
    27  HIToolbox                           0x00007fff837c873d SendMenuItemSelectedEvent + 253
    28  HIToolbox                           0x00007fff836937bb _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 101
    29  HIToolbox                           0x00007fff8368af01 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 600
    30  HIToolbox                           0x00007fff8368a4ca _HandleMenuSelection2 + 580
    31  AppKit                              0x00007fff8ce05fb2 _NSHandleCarbonMenuEvent + 250
    32  AppKit                              0x00007fff8cd9b4ad _DPSNextEvent + 2019
    33  AppKit                              0x00007fff8cd9a861 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    34  AppKit                              0x00007fff8cd9719d -[NSApplication run] + 470
    35  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    36  CocosBuilder                        0x0000000100001512 main + 34
    37  CocosBuilder                        0x00000001000014e4 start + 52
    38  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:25:28.307 CocosBuilder[2465:703] NSExceptionHandler has recorded the following exception:
NSRangeException -- **\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
Stack trace:  0x7fff8363e2b8  0x7fff8363d8a0  0x7fff83654677  0x7fff8369a6c1  0x7fff83781c59  0x7fff837c873d  0x7fff836937bb  0x7fff8368af01  0x7fff8368a4ca  0x7fff8ce05fb2  0x7fff8cd9b4ad  0x7fff8cd9a861  0x7fff8cd9719d  0x7fff8d015b88  0x100001512  0x1000014e4  0x3
2012-03-28 21:25:30.409 CocosBuilder[2465:703] cocos2d: Director#setAnimationInterval. Override me
2012-03-28 21:25:47.250 CocosBuilder[2465:703] cocos2d: Director#setAnimationInterval. Override me
2012-03-28 21:25:49.811 CocosBuilder[2465:703] Could not connect the action changedRootObject: to target of class NewDocWindowController
2012-03-28 21:27:39.834 CocosBuilder[2465:703] -[NSNumberFormatter stringByDeletingLastPathComponent]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:27:39.835 CocosBuilder[2465:703] -[NSNumberFormatter stringByDeletingLastPathComponent]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:27:39.836 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83b6c2ae -[NSObject doesNotRecognizeSelector:] + 190
    3   CoreFoundation                      0x00007fff83acce73 ___forwarding___ + 371
    4   CoreFoundation                      0x00007fff83accc88 _CF_forwarding_prep_0 + 232
    5   CocosBuilder                        0x0000000100012b46 -[CCBDocument rootPath] + 54
    6   CocosBuilder                        0x000000010000551f -[CocosBuilderAppDelegate switchToDocument:forceReload:] + 239
    7   CocosBuilder                        0x000000010000a175 -[CocosBuilderAppDelegate reloadResources] + 165
    8   CocosBuilder                        0x0000000100051819 -[ResourceManager updateResourcesForPath:] + 4041
    9   CocosBuilder                        0x00000001000520f9 -[ResourceManager pathWatcher:eventOccurred:] + 73
    10  CocosBuilder                        0x000000010005384a _events_callback + 970
    11  CarbonCore                          0x00007fff86c28cd3 implementation_callback_rpc + 1753
    12  CarbonCore                          0x00007fff86c2857b _Xcallback_rpc + 458
    13  CarbonCore                          0x00007fff86c283aa FSEventsD2F_server + 148
    14  CarbonCore                          0x00007fff86c2830d FSEventsClientProcessMessageCallback + 29
    15  CoreFoundation                      0x00007fff83a3ee42 __CFMachPortPerform + 386
    16  CoreFoundation                      0x00007fff83a3ecac __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 44
    17  CoreFoundation                      0x00007fff83a3e9db __CFRunLoopDoSource1 + 155
    18  CoreFoundation                      0x00007fff83a75117 __CFRunLoopRun + 1895
    19  CoreFoundation                      0x00007fff83a74676 CFRunLoopRunSpecific + 230
    20  HIToolbox                           0x00007fff8363831f RunCurrentEventLoopInMode + 277
    21  HIToolbox                           0x00007fff8363f51b ReceiveNextEventCommon + 181
    22  HIToolbox                           0x00007fff8363f456 BlockUntilNextEventMatchingListInMode + 62
    23  AppKit                              0x00007fff8cd9af5d _DPSNextEvent + 659
    24  AppKit                              0x00007fff8cd9a861 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    25  AppKit                              0x00007fff8cd9719d -[NSApplication run] + 470
    26  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    27  CocosBuilder                        0x0000000100001512 main + 34
    28  CocosBuilder                        0x00000001000014e4 start + 52
    29  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:29:05.546 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:29:05.555 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:29:05.557 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83b6c2ae -[NSObject doesNotRecognizeSelector:] + 190
    3   CoreFoundation                      0x00007fff83acce73 ___forwarding___ + 371
    4   CoreFoundation                      0x00007fff83accc88 _CF_forwarding_prep_0 + 232
    5   Foundation                          0x00007fff831d0e76 -[NSURL%28NSURL%29 initFileURLWithPath:] + 96
    6   Foundation                          0x00007fff831d0dfd +[NSURL%28NSURL%29 fileURLWithPath:] + 47
    7   CocosBuilder                        0x00000001000061ae -[CocosBuilderAppDelegate saveFile:] + 110
    8   CocosBuilder                        0x00000001000084a3 -[CocosBuilderAppDelegate saveDocument:] + 147
    9   CoreFoundation                      0x00007fff83acf75d -[NSObject performSelector:withObject:] + 61
    10  AppKit                              0x00007fff8ce9fcb2 -[NSApplication sendAction:to:from:] + 139
    11  AppKit                              0x00007fff8cf8cfe7 -[NSMenuItem _corePerformAction] + 399
    12  AppKit                              0x00007fff8cf8cd1e -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 125
    13  AppKit                              0x00007fff8cf0a264 -[NSMenu performKeyEquivalent:] + 281
    14  AppKit                              0x00007fff8cf08eb5 -[NSApplication _handleKeyEquivalent:] + 526
    15  AppKit                              0x00007fff8ce00c4e -[NSApplication sendEvent:] + 4282
    16  AppKit                              0x00007fff8cd971f2 -[NSApplication run] + 555
    17  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    18  CocosBuilder                        0x0000000100001512 main + 34
    19  CocosBuilder                        0x00000001000014e4 start + 52
    20  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:29:52.048 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:29:52.049 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:29:52.051 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83b6c2ae -[NSObject doesNotRecognizeSelector:] + 190
    3   CoreFoundation                      0x00007fff83acce73 ___forwarding___ + 371
    4   CoreFoundation                      0x00007fff83accc88 _CF_forwarding_prep_0 + 232
    5   Foundation                          0x00007fff831d0e76 -[NSURL%28NSURL%29 initFileURLWithPath:] + 96
    6   Foundation                          0x00007fff831d0dfd +[NSURL%28NSURL%29 fileURLWithPath:] + 47
    7   CocosBuilder                        0x00000001000061ae -[CocosBuilderAppDelegate saveFile:] + 110
    8   CocosBuilder                        0x00000001000084a3 -[CocosBuilderAppDelegate saveDocument:] + 147
    9   CoreFoundation                      0x00007fff83acf75d -[NSObject performSelector:withObject:] + 61
    10  AppKit                              0x00007fff8ce9fcb2 -[NSApplication sendAction:to:from:] + 139
    11  AppKit                              0x00007fff8cf8cfe7 -[NSMenuItem _corePerformAction] + 399
    12  AppKit                              0x00007fff8cf8cd1e -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 125
    13  AppKit                              0x00007fff8cf0a264 -[NSMenu performKeyEquivalent:] + 281
    14  AppKit                              0x00007fff8cf08eb5 -[NSApplication _handleKeyEquivalent:] + 526
    15  AppKit                              0x00007fff8ce00c4e -[NSApplication sendEvent:] + 4282
    16  AppKit                              0x00007fff8cd971f2 -[NSApplication run] + 555
    17  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    18  CocosBuilder                        0x0000000100001512 main + 34
    19  CocosBuilder                        0x00000001000014e4 start + 52
    20  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:29:53.848 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:29:53.849 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:29:53.850 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83b6c2ae -[NSObject doesNotRecognizeSelector:] + 190
    3   CoreFoundation                      0x00007fff83acce73 ___forwarding___ + 371
    4   CoreFoundation                      0x00007fff83accc88 _CF_forwarding_prep_0 + 232
    5   Foundation                          0x00007fff831d0e76 -[NSURL%28NSURL%29 initFileURLWithPath:] + 96
    6   Foundation                          0x00007fff831d0dfd +[NSURL%28NSURL%29 fileURLWithPath:] + 47
    7   CocosBuilder                        0x00000001000061ae -[CocosBuilderAppDelegate saveFile:] + 110
    8   CocosBuilder                        0x00000001000084a3 -[CocosBuilderAppDelegate saveDocument:] + 147
    9   CoreFoundation                      0x00007fff83acf75d -[NSObject performSelector:withObject:] + 61
    10  AppKit                              0x00007fff8ce9fcb2 -[NSApplication sendAction:to:from:] + 139
    11  AppKit                              0x00007fff8cf8cfe7 -[NSMenuItem _corePerformAction] + 399
    12  AppKit                              0x00007fff8cf8cd1e -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 125
    13  AppKit                              0x00007fff8cf0a264 -[NSMenu performKeyEquivalent:] + 281
    14  AppKit                              0x00007fff8cf08eb5 -[NSApplication _handleKeyEquivalent:] + 526
    15  AppKit                              0x00007fff8ce00c4e -[NSApplication sendEvent:] + 4282
    16  AppKit                              0x00007fff8cd971f2 -[NSApplication run] + 555
    17  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    18  CocosBuilder                        0x0000000100001512 main + 34
    19  CocosBuilder                        0x00000001000014e4 start + 52
    20  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:30:50.695 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:30:50.695 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:30:50.696 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83b6c2ae -[NSObject doesNotRecognizeSelector:] + 190
    3   CoreFoundation                      0x00007fff83acce73 ___forwarding___ + 371
    4   CoreFoundation                      0x00007fff83accc88 _CF_forwarding_prep_0 + 232
    5   Foundation                          0x00007fff831d0e76 -[NSURL%28NSURL%29 initFileURLWithPath:] + 96
    6   Foundation                          0x00007fff831d0dfd +[NSURL%28NSURL%29 fileURLWithPath:] + 47
    7   CocosBuilder                        0x00000001000061ae -[CocosBuilderAppDelegate saveFile:] + 110
    8   CocosBuilder                        0x00000001000084a3 -[CocosBuilderAppDelegate saveDocument:] + 147
    9   CoreFoundation                      0x00007fff83acf75d -[NSObject performSelector:withObject:] + 61
    10  AppKit                              0x00007fff8ce9fcb2 -[NSApplication sendAction:to:from:] + 139
    11  AppKit                              0x00007fff8cf8cfe7 -[NSMenuItem _corePerformAction] + 399
    12  AppKit                              0x00007fff8cf8cd1e -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 125
    13  AppKit                              0x00007fff8cf0a264 -[NSMenu performKeyEquivalent:] + 281
    14  AppKit                              0x00007fff8cf08eb5 -[NSApplication _handleKeyEquivalent:] + 526
    15  AppKit                              0x00007fff8ce00c4e -[NSApplication sendEvent:] + 4282
    16  AppKit                              0x00007fff8cd971f2 -[NSApplication run] + 555
    17  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    18  CocosBuilder                        0x0000000100001512 main + 34
    19  CocosBuilder                        0x00000001000014e4 start + 52
    20  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:31:41.197 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:31:41.198 CocosBuilder[2465:703] An uncaught exception was raised
2012-03-28 21:31:41.198 CocosBuilder[2465:703] -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
2012-03-28 21:31:41.200 CocosBuilder[2465:703](0   CoreFoundation                      0x00007fff83adffc6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff8dda1d5e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff83b6c2ae -[NSObject doesNotRecognizeSelector:] + 190
    3   CoreFoundation                      0x00007fff83acce73 ___forwarding___ + 371
    4   CoreFoundation                      0x00007fff83accc88 _CF_forwarding_prep_0 + 232
    5   Foundation                          0x00007fff831d0e76 -[NSURL%28NSURL%29 initFileURLWithPath:] + 96
    6   Foundation                          0x00007fff831d0dfd +[NSURL%28NSURL%29 fileURLWithPath:] + 47
    7   CocosBuilder                        0x00000001000061ae -[CocosBuilderAppDelegate saveFile:] + 110
    8   CocosBuilder                        0x00000001000084a3 -[CocosBuilderAppDelegate saveDocument:] + 147
    9   CoreFoundation                      0x00007fff83acf75d -[NSObject performSelector:withObject:] + 61
    10  AppKit                              0x00007fff8ce9fcb2 -[NSApplication sendAction:to:from:] + 139
    11  AppKit                              0x00007fff8cf8cfe7 -[NSMenuItem _corePerformAction] + 399
    12  AppKit                              0x00007fff8cf8cd1e -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 125
    13  AppKit                              0x00007fff8d22add4 -[NSMenu _internalPerformActionForItemAtIndex:] + 38
    14  AppKit                              0x00007fff8d0bb3a9 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 138
    15  AppKit                              0x00007fff8cf06b4b NSSLMMenuEventHandler + 339
    16  HIToolbox                           0x00007fff8363e294 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1263
    17  HIToolbox                           0x00007fff8363d8a0 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 446
    18  HIToolbox                           0x00007fff83654677 SendEventToEventTarget + 76
    19  HIToolbox                           0x00007fff8369a6c1 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 398
    20  HIToolbox                           0x00007fff83781c59 SendMenuCommandWithContextAndModifiers + 56
    21  HIToolbox                           0x00007fff837c873d SendMenuItemSelectedEvent + 253
    22  HIToolbox                           0x00007fff836937bb _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 101
    23  HIToolbox                           0x00007fff8368af01 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 600
    24  HIToolbox                           0x00007fff8368a4ca _HandleMenuSelection2 + 580
    25  AppKit                              0x00007fff8ce05fb2 _NSHandleCarbonMenuEvent + 250
    26  AppKit                              0x00007fff8cd9b4ad _DPSNextEvent + 2019
    27  AppKit                              0x00007fff8cd9a861 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
    28  AppKit                              0x00007fff8cd9719d -[NSApplication run] + 470
    29  AppKit                              0x00007fff8d015b88 NSApplicationMain + 867
    30  CocosBuilder                        0x0000000100001512 main + 34
    31  CocosBuilder                        0x00000001000014e4 start + 52
    32  ???                                 0x0000000000000003 0x0 + 3)
2012-03-28 21:31:41.201 CocosBuilder[2465:703] NSExceptionHandler has recorded the following exception:
NSInvalidArgumentException -- -[NSNumberFormatter length]: unrecognized selector sent to instance 0x10dc13bd0
Stack trace:  0x7fff8363e2b8  0x7fff8363d8a0  0x7fff83654677  0x7fff8369a6c1  0x7fff83781c59  0x7fff837c873d  0x7fff836937bb  0x7fff8368af01  0x7fff8368a4ca  0x7fff8ce05fb2  0x7fff8cd9b4ad  0x7fff8cd9a861  0x7fff8cd9719d  0x7fff8d015b88  0x100001512  0x1000014e4  0x3
2012-03-28 21:31:43.125 CocosBuilder[2465:703] cocos2d: Director#setAnimationInterval. Override me
2012-03-28 22:31:15.539 CocosBuilder[2465:703] cocos2d: Director#setAnimationInterval. Override me
2012-03-28 22:31:18.961 CocosBuilder[2465:703] cocos2d: Director#setAnimationInterval. Override me

**Comment by vlidholt** [comment]
I think that this bug has been fixed on the last version on GitHub (master branch), can you confirm that it is fixed or is the problem still there?

**Comment by adamlwgriffiths** [comment]
I can confirm this is fixed.
Looks like it might have been issue #7

Cheers,
Adam
