### ISSUE TITLE
CCBReader.m error with Cocos1.1

### ISSUE THREAD

**Issue by adamlwgriffiths** [cocos2d/CocosBuilder#15]
Cocos 1.1 doesn't have the static accessor +sharedFileUtils.
It seems this was added in the following commit to Cocos2
https://github.com/cocos2d/cocos2d-iphone/commit/e2b3e728666913864e5b0336d4dc1e860d38f9fb#diff-12

This triggers the error:

Class method '+sharedFileUtils' not found (return type defaults to 'id')

```
- (id) initWithFile:(NSString*)file owner:(id)o
{
    self = [super init];
    if (!self) return NULL;

    // Load binary file
    NSString* path = [[CCFileUtils sharedFileUtils] fullPathFromRelativePath:file];
    data = [[NSData dataWithContentsOfFile:path] retain];
<snip>
```

Kobold2D doesn't use Cocos2.0 so this is breaking CCBReader out of the box.

The fix for me is to remove the static accessor and use the static functions.

```
NSString* path = [CCFileUtils fullPathFromRelativePath:file];
```

**Comment by vlidholt** [comment]
The static functions are no longer present in cocos2d 2.0. I'll see if this can be fixed with a #define. I am only testing CocosBuilder with cocos2d 2.0.
