### ISSUE TITLE
Animating position in timeline disrupts CCMoveTo in code

### ISSUE THREAD

**Issue by ygee07** [cocos2d/CocosBuilder#156]
When I animate the scale of a CCNode using the CocosBuilder timeline, my code "CCMoveTo" works well. 

But when I animate the position of the CCNode using the timeline, "CCMoveTo" no longer works properly (doesn't work at all, it doesn't obey any position).

I do a starting animation of a Scene using Cocosbuilder timeline, but then would like to animate by code after the starting animation for the User Interaction. Please help, thank you.

Using CocosBuilder v2.1 and Kobold2D 2.0.4

**Comment by vlidholt** [comment]
As long as CCAnimationManager isn't running it should be possible to do your own animations. Ie don't use chained animations.
