### ISSUE TITLE
Loading latest files fails

### ISSUE THREAD

**Issue by adamlwgriffiths** [cocos2d/CocosBuilder#16]
I'm getting a failure in CCBReader::readHeader

the magic value is the following in local variables.

```
magic   int <?xm
```

This fails the version check.

**Comment by vlidholt** [comment]
In CocosBuilder 1.1, you need to publish your files to ccbi before loading them through the CCBReader. This ccbi file format is a binary format which is a lot quicker to load.

**Comment by adamlwgriffiths** [comment]
Ah, thanks for that. I didn't realise.
Cheers,
Adam
