### ISSUE TITLE
Zoom button is disabled when create a new project

### ISSUE THREAD

**Issue by yezhstudio** [cocos2d/CocosBuilder#162]
Open CocosBuilder without any project, then create a new project, create a new file.
you'll find the zoom button is disabled, can't use.

**Comment by yezh** [comment]
Create new project or new file will begin a modal sheet(save dialog) by "beginSheetModalForWindow" mothod, this method will restore all toolbar item enabled status after it closed.

zoom button enabled is bind to "hasDocument" key, and this value will change in "beginSheetModalForWindow"'s completionHandler, which would be invoke before save dialog closed.

So. If Zoom button is disabled before "create new", then it will be changed to enabled in completionHandler, then restore to disabled by modal dialog closed.

**Comment by vlidholt** [comment]
This is fixed in latest release!
