### ISSUE TITLE
Can't switch particle color

### ISSUE THREAD

**Issue by TrueTempleDog** [cocos2d/CocosBuilder#165]
Trying to set colors of particles (Mac 10.6.8, CocosBuilder 2.1).  Color doesn't update, and when i click off then reselect the emitter, the color has switched back to default.  All other settings seem to update fine.  Please help!

**Comment by vlidholt** [comment]
Only Mac OS X 10.7 and later is supported by CocosBuilder (there should probably be a warning when starting)
