### ISSUE TITLE
Sub-CCB visibility bug?

### ISSUE THREAD

**Issue by Nuno-Monteiro** [cocos2d/CocosBuilder#169]
Hello!
First of all congratulations for the amazing work you've done with this tool!
I've been testing it to see if it suits my needs and I am very pleased with the results so far.

While testing the loading of a ccb file inside another ccb file I came across an issue:

-If you set the visible flag to false on the sub-ccb file it still shows up when loading the scene

After digging for a while I found this piece of code on readNodeGraph function around line 904:

```
    CCNode* embeddedNode = ccbFileNode.ccbFile;
    embeddedNode.position = ccbFileNode.position;
    //embeddedNode.anchorPoint = ccbFileNode.anchorPoint;
    embeddedNode.rotation = ccbFileNode.rotation;
    embeddedNode.scale = ccbFileNode.scale;
    embeddedNode.tag = ccbFileNode.tag;
    embeddedNode.visible = YES;
```

I changed the last line to:
       //embeddedNode.visible = YES;
       embeddedNode.visible = ccbFileNode.visible;

Now it behaves as I expected it to. Am I seeing this wrong or is this a valid fix?

Thanks!

**Comment by Tw0bit** [comment]
There have been a few issues with Animating Sub-CCB files. The current solution is to wrap a CCNode around the CCB file and run any "non-ccb" animations on it.

CCNode - Parent for CCB: Visible = NO
      >> CCBfile: No Animations

**Comment by Nuno-Monteiro** [comment]
Thanks for the reply!
I'm not really talking about animating a sub-CCB file but I can imagine the same problem happening when you try doing that. 
I've been using sub-CCB files for laying out complex menu scenes with pop-ups and after I changed two lines on the piece of code that I posted I was able to do everything that I wanted to.

So basically I changed this

CCNode\* embeddedNode = ccbFileNode.ccbFile;
    embeddedNode.position = ccbFileNode.position;
    //embeddedNode.anchorPoint = ccbFileNode.anchorPoint;
    embeddedNode.rotation = ccbFileNode.rotation;
    embeddedNode.scale = ccbFileNode.scale;
    embeddedNode.tag = ccbFileNode.tag;
    embeddedNode.visible = YES;

Into this
CCNode\* embeddedNode = ccbFileNode.ccbFile;
    embeddedNode.position = ccbFileNode.position;
    embeddedNode.anchorPoint = ccbFileNode.anchorPoint;
    embeddedNode.rotation = ccbFileNode.rotation;
    embeddedNode.scale = ccbFileNode.scale;
    embeddedNode.tag = ccbFileNode.tag;
    embeddedNode.visible = ccbFileNode.visible;

This way I can layout popups for menus with custom positions, anchor-points and visibility. I can even animate their appearance. I just posted this question because I'm not really sure if I'm damaging any other editor feature that I'm not currently using.

**Comment by vlidholt** [comment]
I believe that this has been fixed in v3.
