### ISSUE TITLE
Included CCControl fails with Cocos1.1

### ISSUE THREAD

**Issue by adamlwgriffiths** [cocos2d/CocosBuilder#17]
The CCControl version used by CCBuilder is currently pointing at an older version.
This has an issue that causes an issue in Cocos1.1.

I raised this issue on the CCControl repo before I realised it was the submodule version.

https://github.com/YannickL/CCControlExtension/issues/3

The issue is that touchDispatcher is not a member of CCDirector.

Lines 161 and 170 of CCControl.m
Property 'touchDispatcher' not found on object of type 'CCDirector *'

```
- (void)onEnter
{
#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
    CCTouchDispatcher * dispatcher = [CCDirector sharedDirector].touchDispatcher;
    [dispatcher addTargetedDelegate:self priority:defaultTouchPriority_ swallowsTouches:YES];
#endif
    [super onEnter];
}

- (void)onExit
{
#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
    CCTouchDispatcher * dispatcher = [CCDirector sharedDirector].touchDispatcher;
    [dispatcher removeDelegate:self];
#endif

    [super onExit];
}
```

This is fixed in the latest versions of CCControl.

**Comment by vlidholt** [comment]
This is fixed with the latest commit to the main branch (only a few hours ago). See the README.md file for info on how to update (you may need to remove lines in .git/config) if you have a version checked out already.

Thanks for all your bug reports! Keep them coming :)

**Comment by adamlwgriffiths** [comment]
Thanks, I appreciate your speedy response. I apologise if I'm posting for things you're currently fixing / have fixed. I can tell you're in the middle of some changes =).

**Comment by adamlwgriffiths** [comment]
Turns out the git submodule is referencing the gles20 branch of the CCControl repo.
This repo still has the issue.
https://github.com/YannickL/CCControlExtension/blob/gles20/CCControlExtension/CCControl/CCControl.m

I've re-opened my issue on their repo.
