### ISSUE TITLE
animation cancels out node animation

### ISSUE THREAD

**Issue by carmandale** [cocos2d/CocosBuilder#170]
I have a ccb node with a sprite and looping animation (fly wing flapping) rotation keys only

I bring that into a full screen ccb layer - flapping works as expected.

If I set a position keyframe on the node (to fly it around the screen), it cancels out or stops the wing flap animation. I might expect that a position keyframe would cancel out the node's position key frame, but it would be extremely useful to have the rotation keyframes carry through.

Also, if you embed a node into another node, it would be nice to have the animation carry through so that you could get nice layered animations
...hope that makes sense.

**Comment by vlidholt** [comment]
Possibly a bug, will try this out.

**Comment by vlidholt** [comment]
I think this should have been fixed, if not please reopen and if possible include a test case.
