### ISSUE TITLE
Why cocosbuilder copies empty folders into the project folder ?

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos2d/CocosBuilder#174]
Hello,

I don't know why cocosbuilder create empty folders into the project folder.

Cocosbuilder can't open projects with lot of subdirectories.
So I set all my ressources paths in the projects settings because I got too many directories in my project.

But all folders and subfolders in my ressources paths are duplicated in my project folder.

Eg:

Project folder 
game/ccb/Game.ccbproj

Ressources folders

I just added the "hero" dir into the ressource path
game/hero/

This folder contains subfolders:
game/hero/stand
game/hero/run
game/hero/jump

Cocosbuilder will create all subdirectories when I publish a ccbi file.

game/ccb/hero/stand
game/ccb/hero/run
game/ccb/hero/jump

And all folders are empty.

Cocosbuilder create too many empty dir and a warning message appears: "Too many Directories"

Cocosbuilder doens't want too many subdirectories but It creates empty folders for nothing...

**Comment by vlidholt** [comment]
Have you tried the option to only publish the ccb files? Otherwise, make sure that your publish path is not inside any of the source paths.

**Comment by BenoitFreslon** [comment]
Have you tried the option to only publish the ccb files ?

This option is always checked.
