### ISSUE TITLE
CocosBuilder Example build failed

### ISSUE THREAD

**Issue by qichunren** [cocos2d/CocosBuilder#178]
I got 7 error when I try to build Cocos2dExample.

<pre>
  "_cc_fps_images_hd_len", referenced from:

  "_cc_fps_images_hd_png", referenced from:

  "_cc_fps_images_ipadhd_len", referenced from:

  "_cc_fps_images_ipadhd_png", referenced from:

  "_cc_fps_images_len", referenced from:

  "_cc_fps_images_png", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols for architecture i386:
  "_cc_fps_images_hd_len", referenced from:
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
  "_cc_fps_images_hd_png", referenced from:
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
  "_cc_fps_images_ipadhd_len", referenced from:
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
  "_cc_fps_images_ipadhd_png", referenced from:
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
  "_cc_fps_images_len", referenced from:
      -[CCDirector getFPSImageData:lenght:] in CCDirector.o
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
  "_cc_fps_images_png", referenced from:
      -[CCDirector getFPSImageData:lenght:] in CCDirector.o
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
      -[CCDirector getFPSImageData:lenght:] in CCDirector.o
      -[CCDirectorIOS getFPSImageData:lenght:] in CCDirectorIOS.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

My env:
Lion 10.8.2
Xcode 4.5.2
Latest Cocos2dBuilder source from github master.

Who can help me to fix this?

**Comment by jmying** [comment]
me too

**Comment by jmying** [comment]
my system is macos x10.8 and xcode use 4.5.

**Comment by MadPig** [comment]
The project isn't setup 100% properly. There are missing cocos files and there are some class .m files not listed in the "compile sources" step of build phases.  

To fix, download http://cocos2d-iphone.googlecode.com/files/cocos2d-iphone-2.1-beta4.tar.gz
Put the cocos2d, CocosDenshion and kazmath folders in the libs directory under your xcode project. (using file system). The cocosDenshion folder you want to copy is in the cocosDension folder. Don't copy the parent one. The cocosDension folder you copy should have no folders in it (unlike the parent folder).
You'll find the kazmath folder in the external directory.

In the xcode project, select the folders, cocos2d, CocosDenshion and kazmath. hit delete. Select "remove reference".
Now drag and drop from the finder to Xcode those three folders. drop them in the libs folder (group) in xcode. Make sure the add to targets has a check on your project target. Copy items to destination group should be checked. Create groups for any added folders should be on. 

After that, it should build. 

Cheers,
MadPig

**Comment by vlidholt** [comment]
Fixed (on develop branch).
