### ISSUE TITLE
CocosBuilder using image from frameCache crashes due to ccbResource/xxxx.plist relative path thing

### ISSUE THREAD

**Issue by mcpoet** [cocos2d/CocosBuilder#185]
Hi, all:
    I 've used CocosBuild for some sprite animations from image frames specified by a .plist file, and the CCFileUtils just cannot find the plist resource as it is addressed as ccbResource/xxx.plist .
     Is there any solution for this bug ?

**Comment by vlidholt** [comment]
Yes, you can either check the "Flatten file paths" option in the publishing settings, or you can add the resources as a blue folder in Xcode
