### ISSUE TITLE
Add support for 'capInsets' on CCButton / CCScale9Sprite

### ISSUE THREAD

**Issue by adamlwgriffiths** [cocos2d/CocosBuilder#19]
CCButton and CCScale9Sprite have a constructor parameter that lets you specify the size of the caps.

See the last parameters in the first code example on this page:
http://yannickloriot.com/2011/12/create-buttons-in-cocos2d-by-using-cccontrolbutton/

**Comment by vlidholt** [comment]
This has been added for CCScale9Sprite

**Comment by bobmoff** [comment]
I dont think this is implemented that same way in the app as the class.

In CocosBuilder it goes X pixels from each side. Top, Right, Bottom and Left, but that is not how it works. The class uses a CGRect to define the middle square part of the image that should be stretched in both directions.

Instrcutions: http://yannickloriot.com/2011/12/create-buttons-in-cocos2d-by-using-cccontrolbutton/
