### ISSUE TITLE
CCBReader memory leak in nodeGraphFromData:owner:parentSize:

### ISSUE THREAD

**Issue by jison** [cocos2d/CocosBuilder#190]
```
    node.userObject = manager; 
```

here, node.userObject retain animationManager;

and in 

CCNode\* nodeGraph = [self readFileWithCleanUp:YES actionManagers:animationManagers];
------- (CCNode_) readNodeGraphParent:(CCNode_)parent
----------------if (!actionManager.rootNode)   actionManager.rootNode = node;

here actionManager.rootNode retain node;

so, it's a cycle refence. the node can not dealloc

**Comment by jdmunro** [comment]
Which version was this in?

```
actionManager.rootNode = node;
```

This line doesn't actually retain the node, if you check the declaration of the property you'll see that this is an assign. But perhaps this has only recently changed?

```
@property (nonatomic,assign) CCNode* rootNode;
```

**Comment by jison** [comment]
oh, the CCBReader source code has update to a new repository, and i can't find out the version of that code. sorry for that. And the new code seems ok.
