### ISSUE TITLE
The CCLabelBMFont couldn't save Blend alpha

### ISSUE THREAD

**Issue by lamquangminh** [cocos2d/CocosBuilder#191]
Hi,
I want to save the Blend Alpha to {One, One - Src Alpha} but it's still {Src Alpha, One - Src Alpha}
Please help me,

Thanks,
Quang Minh

**Comment by morieris** [comment]
I'm having this same issue - setting {One, One - Src Alpha} for a ccLabelBMFont, either manually or from the "Normal" button, will not persist after saving and reloading the file, or after publishing the file.  The node reverts to having {Src Alpha, One - Src Alpha} after reload.

Setting the node to {One, One} ("Additive") works as expected.
