### ISSUE TITLE
CCBFile content size property

### ISSUE THREAD

**Issue by haligalaph** [cocos2d/CocosBuilder#195]
It is very inconvenient, that content size property is blocked in CCBFile node. When you develop ccb-scene, sometimes its size can't be precisely estimated. And only in parent node you can determine it. And it could be different in different parent nodes.

**Comment by vlidholt** [comment]
Not sure how you mean. The contentSize of the root node in a ccb-document can be set (either to a relative or fixed size). Care to elaborate?

**Comment by haligalaph** [comment]
I mean, that you can't rewrite its contentSize in other ccb-documents, which include it as a child. Setting contentSize in the origin ccb-document will affect on all its instances in other documents. But sometimes contentSize should be different in different scenes. At the moment I can solve this problem by adding one extra CCNode. I set width and height of the root node in a child-document 100% "percentage of container size". And then in parent-document I add accessory CCNode with required contentSize that contains CCBFile-node as a child. But it is not quite convenient. Ccb-document, which has root node with relative size, looks awkward in editor with all its children gathered in one point.
