### ISSUE TITLE
 Add Effects

### ISSUE THREAD

**Issue by samadiqbal** [cocos2d/CocosBuilder#198]
Hey!

Recently switched from animating in After Effects to CocosBuilder since im working on games now. Great software. Just a few suggestions that would really help in the animation process. 

Presently I can use the color option to make a certain image completely black, It would be really helpful if I had an option to make an image completely white. Other effects commonly found on AE such as Glow and Levels would also be a great addition. 

Please let me know if and when they can be incorporated in the software. 

![Screen Shot 2012-12-20 at 5 21 29 PM](https://f.cloud.github.com/assets/3089593/24342/0a8ef372-4aa0-11e2-9e99-290db7893bb9.png)
Glow effect from AE

**Comment by vlidholt** [comment]
This would be more of a feature request for cocos2d (so please post it there). Problem is there is no easy way to do this, it's possible that it could be done with shaders, but I am not sure.
