### ISSUE TITLE
Set Timeline Duration... can not be used!

### ISSUE THREAD

**Issue by minihope** [cocos2d/CocosBuilder#200]
To set the length of the animation by clicking on the time display below the canvas area name's Set Timeline Duration...? But nothing happens..
I can't change the timeline duration..

this's a bug, right?

cocosbuilder 2.1 & cocosbuilder 3.0 both

the operating system is Snow Leopard 10.6.8

**Comment by ikermendi** [comment]
Same problem here. 

I can change the timeline duration only in one timeline. If I add another timeline and change the duration nothing happens.

Mountain Lion 10.8.2
CocosBuilder 2.1

**Comment by vlidholt** [comment]
I cannot reproduce this bug (only testing on latest version on develop branch).
