### ISSUE TITLE
Problem with creating a new Layer document

### ISSUE THREAD

**Issue by Mahdi7s** [cocos2d/CocosBuilder#203]
Hi all,
every time I want to create a layer document(from File -> New -> New File...) after setting layer location and name I will see a black useless layer in the center of application; below is an image that shows the problem: 

![bl](https://f.cloud.github.com/assets/1885293/35901/f77ec406-5292-11e2-9688-23b2e54f7746.png)

In addition, I can't delete a ccb file from delete menu(I can do this only using finder): 
![dm](https://f.cloud.github.com/assets/1885293/35914/87eb4198-5295-11e2-816f-761fa12bdcb2.png)

Edit:
Another thing:  occasionally, when I create a new project, my application screen is looks like below: 
![Screen Shot 1391-10-11 at 4 09 05 PM](https://f.cloud.github.com/assets/1885293/36519/cd154c0c-5347-11e2-9053-a803fa0e55bb.png)

I have v2.1 stable of Cocosbuilder!

**Comment by vlidholt** [comment]
I cannot reproduce your 1st & 3rd issue, which version of Mac OS X are you using? As for your second point, this has not yet been implemented.

**Comment by Mahdi7s** [comment]
hi vlidholt,

my Mac OS X version is 10.8

thanks

**Comment by tom1199** [comment]
i have problem with creating the new document file. 
whenever i create new ccb file with root object type CCLayer, i can't see new ccb file created in the project window, neither on  project directory folder. any input?
