### ISSUE TITLE
Disabling Javascript in 3.0

### ISSUE THREAD

**Issue by jessbowers** [cocos2d/CocosBuilder#206]
Is there a way to disable the "Javascript Controlled" when publishing with 3.0?  I tried the following to no effect:
- Project Settings: uncheck "Javascript based project"
- open each CCB file, uncheck "Javascript Controlled" (although these don't stick when file is reopened)
- Cleaned project, deleted generated resource directory

However, as far as I can tell, it still seems to publish with the jsControlled = YES in the CCBI

**Comment by vlidholt** [comment]
It did in fact work, but did not mark the document as dirty (so you were never prompted to save).
