### ISSUE TITLE
Application crashes when publishing ccbi file with spritesheet animation.

### ISSUE THREAD

**Issue by rbvea** [cocos2d/CocosBuilder#211]
I've exported an swf animation to a spritesheet and used the plist to generate keyframes for a CCSprite.  Publishing both the layer and the sprite itself caused the application to crash.

The report log can be seen here: 

Process:         CocosBuilder [803]
Path:            /Applications/CocosBuilder.app/Contents/MacOS/CocosBuilder
Identifier:      com.cocosbuilder.CocosBuilder
Version:         2.1 (2.1)
Code Type:       X86-64 (Native)
Parent Process:  launchd [160]

Date/Time:       2013-01-16 12:40:40.814 -1000
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          189500 sec
Crashes Since Last Report:           15
Per-App Interval Since Last Report:  4178 sec
Per-App Crashes Since Last Report:   15
Anonymous UUID:                      23348EDF-8E2A-4423-9D5E-44A17A1E9114

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Crashed Thread:  5  Dispatch queue: com.apple.root.default-priority

Application Specific Information:
abort() called
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ccbi export: Trying to write string not added to cache (Slippery.swf/0001)'

**Comment by vlidholt** [comment]
Can you provide a test case, preferably a project within a zip file that is as small/simple as possible?

**Comment by rbvea** [comment]
Here is a .zip that contains a spritesheet, plist and a ccb file with two keyframes generated by using "Create Keyframes from Selection".  It does not publish.

http://dl.dropbox.com/u/8731753/ccb_crash_test_case.zip

**Comment by vlidholt** [comment]
Fixed (on develop branch)! Thanks for the test case :)
