### ISSUE TITLE
[Improvement] Add a '*' next to the ccb filename in the Project pane.

### ISSUE THREAD

**Issue by ubimtl-sdenis** [cocos2d/CocosBuilder#217]
Add a '\* or small special character' next to the CCB filename in the Project pane when a file has been modified, so we know that it needs to be saved.

**Comment by vlidholt** [comment]
It's already marked as dirty in the tabs at the top of the window.

**Comment by ubimtl-sdenis** [comment]
Indeed, it was not very visible. Thanks.
