### ISSUE TITLE
[Improvement] Add a 'Save All' and proposes it when closing the editor.

### ISSUE THREAD

**Issue by ubimtl-sdenis** [cocos2d/CocosBuilder#218]
Add a 'Save All' option and proposes it when closing the editor.

**Comment by pierrepaullavoie** [comment]
I like this feature; it would be nice to have the option of being notified if you are about to run the game in CocosPlayer and have any unsaved file. The user could then be presented with the "Save All" option in the dialog.

**Comment by pierrepaullavoie** [comment]
Proposed solution in #235 for original poster.

**Comment by vlidholt** [comment]
This feature has now been added on develop branch.
