### ISSUE TITLE
Sprite displays wrong positions under IPhone4S which has 960x640 resolution

### ISSUE THREAD

**Issue by doneykoo** [cocos2d/CocosBuilder#22]
Steps:
In builder, change the stage size to custom 960 x 640
Create a menu
Add a Sprite
Set sprite texture with a PNG of about 200 x 200
Set sprite is relative anchor point
Set sprite anchor point 0.5,  0.5 
Set sprite position to 480, 320
Run app with this menu resource, onto IPhone4S which has 960x640 resolution

Result:
Such sprite is displayed at the corner of the screen.

Expected:
Such sprite shall be displayed at the center of the screen.

**Comment by vlidholt** [comment]
CocosBuilder works in points (not pixels), which means that you should use a 480 x 320 resolution for iPhone4S.
