### ISSUE TITLE
CCB Publish System causes errors in copied files

### ISSUE THREAD

**Issue by Clarinexus** [cocos2d/CocosBuilder#23]
In a ccb file, the export path is overwritten when a user clicks publish as, but the user must then save the ccb for the changes to take place.  This has led to bad export paths in a lot of ccbs.  If the export path was treated as an exception, with no path defaulting to the filename, then creating new ccbs out of old ones would be less of a problem.  

Also, if Publish As automatically saved the new path in the ccb instead of asking the user, it would also speed things up.

**Comment by vlidholt** [comment]
CocosBuilder is now using relative paths for saving the publish location. An improved publish system is in the roadmap.
