### ISSUE TITLE
Basic CCAction support

### ISSUE THREAD

**Issue by Zakay** [cocos2d/CocosBuilder#24]
I would love it if you could set an action on a node.

e.g:
A sprite: I give it a Start animation:
- When the menu has appeared, the sprite starts outside the screen.
  Then during 1 second animate in the sprite with EaseOut until correct position.

So ability to choose starting position and ending position, an animation (easeout), and a duration.

I would just start with the basics in the beginning, just allow some predefined animations:
- Slide, linear, easein, easeout, easein/out, bounce

Thats it :)

**Comment by vlidholt** [comment]
Very good suggestion. An action editor is in the road map. See http://www.cocos2d-iphone.org/forum/topic/31157
