### ISSUE TITLE
cocosplayer:the lasted cocosplayer has a bug,please fixes

### ISSUE THREAD

**Issue by LibreChou** [cocos2d/CocosBuilder#243]
this is the lasted cocosplayer.images cannot show,I hope to fix it.
![cocosplayer](https://f.cloud.github.com/assets/1937656/121796/6dbf09e6-6dfa-11e2-8943-a2b5c64bb843.jpg)

**Comment by many20** [comment]
i have the same bug
it occurs only on devices in retina mode

with `self.hasRetinaDisplay = [director_ enableRetinaDisplay:YES];`
set to "NO" works fine, but than its not retina.

**Comment by LibreChou** [comment]
It is OK! Thanks

**Comment by vlidholt** [comment]
I am getting the same error now. Will look into this.

**Comment by vlidholt** [comment]
See this thread for a temporary fix: http://www.cocos2d-iphone.org/forum/topic/215577 Will update and release a new version of CocosBuilder shortly.
