### ISSUE TITLE
EXC_BAD_ACCESS in CCBReader on device

### ISSUE THREAD

**Issue by ghroot** [cocos2d/CocosBuilder#244]
When the following conditions are met CCBReader will crash:
- Running on device
- Built with iOS SDK 6.1 (not sure if this makes a difference but the crash started happening recently)
- Optimisation set to "Fastest/smallest"
- At least one node has a position that is not whole pixels (e.g. 50.5)
- The ccbi file is being parsed

Related forum post: http://www.cocos2d-x.org/boards/6/topics/18183 (relates to cocos2d-x but also happens on cocos2d-iphone). The same fix works on cocos2d-iphone as well.

**Comment by ghroot** [comment]
This is potentially a fairly big issue as apps loading ccbi files could suddenly start crashing ONLY on devices and ONLY with the highest optimisation build setting that is usually only enabled for release builds.

**Comment by vlidholt** [comment]
Please see here for a quick fix: http://www.cocos2d-iphone.org/forum/topic/214075 this issue has been fixed on last release.
