### ISSUE TITLE
Couldn't load .ccb file made by cocosbuilder 1.0, even fail when building the samples

### ISSUE THREAD

**Issue by 4everlove** [cocos2d/CocosBuilder#26]
Hi,

Thanks first for your spectacular work. CocosBuilder 1.0 has helped me a lot. However, due to some reasons I have to migrate to cocosbuilder 1.1 in order to do some customization. I've built CocosBuilder 1.1 along with cocos2d-iphone-2.0-rc0.tar.gz. While try my own project (migrated to cocos2d 2.0 with ccb created by CocosBuilder 1.0 already) and the samples, I fail to run them as the following exceptions:

My own app:

(I try to use CocosBuilder 1.1 to open my ccb files created by v1.0)
cocos2d: WARNING: Not enough memory to resize the atlas
XXX: CCSpriteBatchNode#increaseAtlasCapacity SHALL handle this assert

Sample with 1.1:

The same error.

I'm new to cocos2d so I have a little trouble with solving this problem. Will you please give me some hint or solution?

Thanks,
Alan

**Comment by 4everlove** [comment]
More details:

For my own app: the exception was caught when I used CocosBuilder through XCode to load my old ccb files
For sample app: normal execution

It seems loading ccb files which contains CCLabelBMFont will raise such an exception (CCLabelBMFont inherits CCSpriteBatchNode)

By watching the breakpoint I can figure out the reason why the execution flow enters the block of these prompts is because textureAtlas_ is nil.

**Comment by 4everlove** [comment]
OK I think I got the answer to this. This exception was thrown because either CocosBuilder or CCBReader.m treats CCLabelBMFont as a plain control and using [xxx setValue:fntFile forKey:xxx] for property setting. However, without explicitly calling -initWithString:fntFile: or +labelWithString:fntFile:, CCLabelBMFont will not initialize its super class, namely CCSpriteBatchNode, which means there is no way to create an instance and assign it to textureAtlas_. Therefore, whenever setting string or some sort of operations having to do with -createFontChar or something, which invokes CCSpriteBatchNode#increaseAtlasCapacity, will fail due to the nil pointer of textureAtlas_.

Is this a bug of CocosBuilder? 'Cause I think making class instantiation in a general way has shown a lack in accommodating some explicit initialization requirement of cocos2d

**Comment by vlidholt** [comment]
You need to build CocosBuilder with the latest version of the cocos2d gles20 branch. Will double check backwards compatibility with file format.

**Comment by vlidholt** [comment]
To use the latest/correct version of cocos2d make sure you do a

git submodule init
git submodule update

before compiling CocosBuilder
