### ISSUE TITLE
Where is fresh CCBReader

### ISSUE THREAD

**Issue by AlexanderBykin** [cocos2d/CocosBuilder#268]
Hi.

Have this error:
CCBReader: Incompatible ccbi file version (file: 5 reader: 4)

at ios project, where can i find fresh version of CCBReader ?

Trying to use all i can find at repo, but no luck, anyway error.

Thanks.

**Comment by vlidholt** [comment]
The additions for CCBReader should now have been merged into the cocos2d-iphone develop-v2 branch. You will also need to update the submodules. Updates have not yet been made to cocos2d-x and cocos2d-html5, but are scheduled for the next few weeks.

Best,
Viktor

**Comment by musehu** [comment]
Hi~ i have another problem...

CCBReader: Incompatible ccbi file version (file: 4 reader: 5)

in my project, the "CCBReader.h" has the "#define kCCBVersion (5)" ,
so,  Which version of CocosBuilder can publish the file version (5) of ccbi ?

All the Best,
Steven

**Comment by petroslafaz** [comment]
I had the same problem, and I fixed it by using the develop branch of CocosBuilder.

**Comment by pierrepaullavoie** [comment]
Looks like #278 might help.
