### ISSUE TITLE
On a retina display images get scaled down but not the positions

### ISSUE THREAD

**Issue by Bergamott** [cocos2d/CocosBuilder#28]
Run the CocosBuilderExample in the emulator with Hardware->Device set to "iPhone (Retina)". The sprites are located properly relative to the screen, but have only half their intended size. This makes it impossible to get WYSIWYG in the editor when designing for retina displays. Coordinates appear to be in points, while sprite sizes are in pixels.

**Comment by vlidholt** [comment]
You need to add images with the -hd suffix in double resolution, cocos2d doesn't automatically scale images up.
