### ISSUE TITLE
"Only publish ccb-files" also publishes empty folders

### ISSUE THREAD

**Issue by MKGitHub** [cocos2d/CocosBuilder#281]
"Only publish ccb-files" also publishes empty folders and nested empty folders.

I've added some folders to the Resources path so that the resources are available in the project, but then I just want to publish the ccb/ccbi - but then all the folders in my Resources path are also published, but atleast they are empty.

If I choose to publish only the ccb/ccbi, then only that should be published.
![Screenshot 2013-03-23 at 01 50 25](https://f.cloud.github.com/assets/535550/293281/be35d3cc-9353-11e2-88e9-0c0084cd5fa4.png)
![Screenshot 2013-03-23 at 01 51 32](https://f.cloud.github.com/assets/535550/293282/d52710be-9353-11e2-86d4-d17caf7342e8.png)

**Comment by vlidholt** [comment]
This should be an extra check inside the CCBPublisher, most likely in the publishDirectory:... method. Directories should still be created if there are ccb-files in them. The current publishing settings can be found in the projectSettings member variable.

**Comment by longyangxi** [comment]
fixed, see the pull request.

**Comment by vlidholt** [comment]
Yay! :)
