### ISSUE TITLE
no log printed in cocosPlayer's console

### ISSUE THREAD

**Issue by l8g** [cocos2d/CocosBuilder#284]
alpha 2 vision can do this

**Comment by pierrepaullavoie** [comment]
I also have the [same issue as described in my forum post](http://www.cocos2d-iphone.org/forum/topic/282952). Also, simply placing cc.log("test") in the CocosPlayer Console and clicking "Run Script" does not print anything.

**Comment by pierrepaullavoie** [comment]
Although it is not appearing in the CocosPlayer Console (CocosBuilder window with Play/Stop) the output is printed in the Xcode output window if you run CocosPlayer from Xcode using the iOS simulator.

**Comment by macgeo** [comment]
having same issue. 

wasn't getting log results in xcode console either, but turns out it was because I was running the player straight from xcode; needed to stop and relaunch

**Comment by vlidholt** [comment]
Oops, there were an error in the uploaded code. Will do a new upload and post here!

**Comment by vlidholt** [comment]
Uploaded new src code zip file!

**Comment by l8g** [comment]
Where I can get the new code? I pull the latest version of code and  find it still no logs

**Comment by gamefish** [comment]
I'm using 3.0 alpha4, In CocosBuilder/CocosPlayer/README.md there is line:

# Enable the Debugger

The latest version of CocosPlayer and CocosBuilder support debugging of JavaScript code. To enable the debugger you need to set JSB_ENABLE_DEBUGGER to 1 in the jsb_config.h file of the CocosPlayer project. If you have downloaded the source code as a zip file, this setting is already done, but if you got the code from GitHub you will need to do it manually.

I tried this, it only works when the CocosPlayer is run from XCode on iPhone.
