### ISSUE TITLE
Also be able to set opacity in % or float

### ISSUE THREAD

**Issue by MKGitHub** [cocos2d/CocosBuilder#287]
It has always been only possible to set the opacity using a Byte 0-255. Please also make it possible to set the opacity in % 0-100 or a float 0.0-1.0.

I.e. like when settings the position, it is possible to choose the range type.

**Comment by vlidholt** [comment]
This would need to be an option of cocos2d. I'm not sure that this will become an option. What is the use case (except convince)?

**Comment by MKGitHub** [comment]
It does not have to be an option in cocos2d, you just convert it to the standard Byte 0-255 on publish. But the user can choose the format he/she wants to use - Byte, Float or Percentage == Major workflow enhancer not have to figure out how much something is of 0-255.

**Comment by MKGitHub** [comment]
Please re-open this issue as I've provided a simple solution in the comment above.

**Comment by pierrepaullavoie** [comment]
How about adding an option that if your input is in floating point format it will automatically convert it to the 0-255 range. This is a simple change that would not require an API update on cocos2d. The workflow would work, provided that the user is aware of this little trick.

A text label next to the input field could be added to always represent the percentage to the user. This way, it is also clear to the user that the API take values ranging from 0 to 255.

**Comment by MKGitHub** [comment]
That is just a workaround. The best method here is to choose the format, enter the value and have it converted to a Byte on publish. No guessing or working with ugly Byte ranges. The only time the user needs to know the API is when actually setting the opacity in code - which only takes a Byte.

**Comment by MKGitHub** [comment]
Guide me where to add this in the code as there is alot of code for CocosBuilder, I could use a helping hand to get around in there and start adding features my self.
