### ISSUE TITLE
Store .ccb/.ccbi files inside a subdirectory and access child folders

### ISSUE THREAD

**Issue by stevekanter** [cocos2d/CocosBuilder#30]
I can best explain it with a [forced redacted] screenshot.

![Child Folders](http://cloud.kanter.me/0B1h371q183O152U471y/content)

So right now i'm forced to save my .ccb/.ccbi files right in the root of Game Resources.  As you can see, also in Game Resources are "Enemies, Fonts, InGameUI, etc".  I need to access resources inside of those folders in my .ccb folder, but would ideally like to add a "CocosBuilder" folder inside of Game Resources, for cleanliness.  Inside my app, I have a few folder references for some resources - such as "InGameUI", but not others, such as "Random".

Here's what I propose to try and fix this:

1) allow a per-ccb preference to set the "root" of the graphics folder - that is, I could store the .ccb files WHEREVER I want, and it will only search from the preference [if the preference isn't set, it defaults to the current location of .ccb].

2) on a per-node basis, allow me to set whether to try and load that image in using an absolute path, or if it's flattened.

With all of that said, here is an example of the ideal behavior i'd like to see:

I'd store all of my .ccb/.ccbi files inside of Game Resources in a folder called "CocosBuilder".  This folder inside of my Xcode project would be a folder reference.

Inside xyz.ccb I would point to a few different resources, some in "InGameUI" [a folder reference] and some in "Random", not a folder reference.

When CCBReader loads in xyz.ccbi, it will determine if the .ccbi provided is indeed in the root app resource folder, or in a sub-directory.  Then, it will adjust any locations as appropriate.  For example, if it determines that xyz.ccbi is in "/[app-location]/Resources/CocosBuilder/xyz.ccbi", when it tries to load in "./InGameUI/def.png", it will always load it as "/[app-location]/Resources/InGameUI/def.png".

I'd be more than willing to help make this possible, as it's a feature that would really help me out - not only to make things neater, but to ensure that my game remains organized, as it's highly resource intensive.

**Comment by vlidholt** [comment]
Thank you for your feedback. In the latest version on GitHub handling of resource directories and sub directories is greatly improved.
