### ISSUE TITLE
Ability to set the suffix for the different image resoultions.

### ISSUE THREAD

**Issue by MKGitHub** [cocos2d/CocosBuilder#308]
In code I can do this:

[sharedFileUtils setEnableFallbackSuffixes: NO];

[sharedFileUtils setiPhoneRetinaDisplaySuffix: @"-retina1"];
[sharedFileUtils setiPadSuffix: @"-retina1"];
[sharedFileUtils setiPadRetinaDisplaySuffix: @"-retina2"];

I have not found a way to set this in CocosBuilder, which is also why I'm not seeing these files in my project for other resolutions in stage (since I'm using a non-standard convention). Please add these options in the project setup or elsewhere.

• Use fallback.
• setiPhoneRetinaDisplaySuffix
• setiPadSuffix
• setiPadRetinaDisplaySuffix

**Comment by vlidholt** [comment]
The new cocos2d standard is to use directories for resolutions. Suffixes are being deprecated.
