### ISSUE TITLE
Certain Changes to CCB files are not published to CCBI

### ISSUE THREAD

**Issue by janvdk** [cocos2d/CocosBuilder#313]
I have noticed that when making some changes, these are not updated in .ccbi files after publishing. When I change the Selector on a CCMenuItem, the .ccbi file is exactly the same after publishing as it was before the change. I checked this by doing a SHA1 of the .ccbi before and after making the change, and both matched. 

In order to ensure that the change is published it's necessary to make some other change, like changing the text on a label. I have also noticed this when when changing the Sprite frame on a CCSprite. Also after saving the scene, quitting and reopening Cocos Builder, these changes are not present. I'm using CocosBuilder 3.0.

Thanks

**Comment by pierrepaullavoie** [comment]
You must make sure to save all your unsaved CCB files before publishing.

Also, if you edit a text field and don't tab out; I've noticed that it won't mark the document as dirty. So make sure to select an other text field to force the dirty indicator to turn no.

This is somewhat related to #255, #218, #235, and is planed feature in the [roadmap](https://github.com/cocos2d/CocosBuilder/blob/develop/Documentation/XX1.%20CocosBuilder%203%20Roadmap.md).

Hope that helps.

Cheers,
ppl

**Comment by janvdk** [comment]
Thanks for the prompt reply. I tried editing the text field, hitting enter, and then saving and publishing which works.

Cheers,
Jan

**Comment by vlidholt** [comment]
I think the need of hitting return key in text-fields is just how Cocoa works, unfortunately. CocosBuilder will now ask you to save all files when publishing.
