### ISSUE TITLE
Automatic Scaling issue

### ISSUE THREAD

**Issue by bonlam** [cocos2d/CocosBuilder#321]
I am using the lastest release of cocosbuilder 3.0.3.

When I use "Automatic Scaling from: 4x" in the publish settings, the texture of the editing area become very blur, which I guess is the non-retina iphone textures.

But actually in the resources-auto folder there are all textures for retina ipad.
I want a better view when I edit my views/sprites.

I don't know whether it is a feature or a bug.

**Comment by vlidholt** [comment]
The design mode in CocosBuilder uses non-retina iPhone or iPad mode. If you need to preview on retina display, you can do so in CocosPlayer.
