### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by zj831007** [cocos2d/CocosBuilder#324]
When I get the latest code from github,  I could not build successful, and the error is:
Lexical or Preprocessor Issue 'CCMenu.h' file not found. 
How to configure the xcode to build cocosbuilder from source code?
Thanks very much!

**Comment by vlidholt** [comment]
Hi! you will need to do a

```
git submodule init --update --recursive
```

after downloading the code (see the read me file for more details)

**Comment by axinyue** [comment]
cd CocosBuilder/libs/cocos2d-iphone/
git checkout 5903152ed4937b44beccb690b1330213b3cbb695
