### ISSUE TITLE
the callbacks keep dispearing on multiple timelines

### ISSUE THREAD

**Issue by emmychen** [cocos2d/CocosBuilder#337]
I created multiple timelines on cocosbuilder. even I saved the work every time I change to another timeline, when I go back to the previous timeline, the callbacks I setup were gone.  

It is very frustrated, I have to keep setting the callbacks all the time, and then they were gone.

**Comment by vlidholt** [comment]
Fixed on develop branch

**Comment by emmychen** [comment]
wow, great.  Thank you for the quick fix!! :)
