### ISSUE TITLE
No logs in CocosPlayer console when launched whitout XCode

### ISSUE THREAD

**Issue by dchis** [cocos2d/CocosBuilder#351]
There are no longs in the CocosPlayer console, only when CocosPlayer is run from the XCode project (Build&Run).

The problem is that the stdout redirect isn't working the same when the app is launched for the device(or simulator) vs when it is debuged from XCode.

The solution is to make stdout line buffered. Credit goes to this gentlemen here http://idevapps.com/forum/archive/index.php/thread-7166.html.

I've fixed this issue by adding the following line: setvbuf(stdout, NULL, _IOLBF, 4069 );
to the redirectStdOut method in ServerController.m in the CocosPlayer project.

Now the logs appear in the console even if CocosPlayers is nit run from XCode.

**Comment by vlidholt** [comment]
Thanks added this line! :)
