### ISSUE TITLE
/* crashes CocosBuilder

### ISSUE THREAD

**Issue by sortris** [cocos2d/CocosBuilder#353]
When I try to comment something out in .js files with
/*
combination, CocosBuilder crashes and I have to reopen it.

Example. I have following code:

<pre>var Krzyzak = function()
{
};

Krzyzak.prototype.onDidLoadFromCCB = function()
{
cc.log("KRZ START");
 this.rootNode.onTouchesBegan = function( touches, event) {
 this.controller.onTouchesBegan(touches, event);
 return true;
    };
};
</pre>

when I try to comment out cc.log line with /\* symbols combination, CocosBuilder crashes.
Crash details: http://pastebin.com/5xH8LyAS

**Comment by vlidholt** [comment]
Fixed on develop branch
