### ISSUE TITLE
tips error in InspectorPosition.xib

### ISSUE THREAD

**Issue by walzer** [cocos2d/CocosBuilder#38]
Tool Tip are wrong in this bar
segment 0: absolute (correct)
segment 1: Percentage of container -> Relative top left
segment 2: Relative top left -> Relative top right
segment 3: Relative top right -> Relative bottom right
segment 4: Relative bottom right -> Percentage of container

**Comment by vlidholt** [comment]
Thank you! This has now been fixed.
