### ISSUE TITLE
How can I create a callbacks of timeline

### ISSUE THREAD

**Issue by happy253650035** [cocos2d/CocosBuilder#383]
![2013-06-14 4 26 25](https://f.cloud.github.com/assets/2668153/653058/251e6d9c-d4cc-11e2-8cc5-01c55a4fddef.png)
I want to create a callbacks in timeline, but I don't know how can I create it. anyone help me?

**Comment by nickveri** [comment]
You have to option key + left click on the "Callbacks" bar.

**Comment by happy253650035** [comment]
haha, it's really! I done it. thanks!
