### ISSUE TITLE
Excessive CPU consumption

### ISSUE THREAD

**Issue by kagakuninja** [cocos2d/CocosBuilder#39]
I have a simple scene with a layer and 2 sprites, the app is using 11% CPU on a i7 quad-core macbook pro.  Since the app is idle, the CPU consumption should be minimal.  I am running code from May 16, 2012.

**Comment by vlidholt** [comment]
To support things such as particle systems cocos2d is running continuously in CocosBuilder. When swapping to another application cocos2d is paused and cpu usage should drop.
