### ISSUE TITLE
zOrder has disappear

### ISSUE THREAD

**Issue by upigames** [cocos2d/CocosBuilder#41]
Beta1 has no zOrder field. Seems its disappear. There's no way to modify this setting.

**Comment by efishocean** [comment]
I need zOrder, it's better than drag tabs up&down.

**Comment by vlidholt** [comment]
zOrder is now set implicitly by CocosBuilder. If you need something placed at a certain depth the recommended way is to add a node as a placeholder and add to it or replace it in your code.

**Comment by upigames** [comment]
Thanks for the info. Now I see how it works...
