### ISSUE TITLE
Too many sub dictionaries on OSX Lion

### ISSUE THREAD

**Issue by ezhes** [cocos2d/CocosBuilder#44]
When ever I try to open a project it states there are too many sub dictionaries around. I then made a folder that didn't have any other folders in it and it still didn't work.

20-inch, Early 2009
Software  Mac OS X Lion 10.7.4 (11E53)
Graphics  NVIDIA GeForce 9400 256 MB
Memory  2 GB 1067 MHz DDR3
Processor  2.66 GHz Intel Core 2 Duo

**Comment by hrmoller** [comment]
Are you opening it from your Downloads folder?
I had the same issue but moving the app from my Downloads folder to my Applications folder and launching CocosBuilder from there did it for me.

**Comment by ezhes** [comment]
Nope, it's in my applications folder

**Comment by vlidholt** [comment]
Make sure that you save your project in an empty directory.

**Comment by ezhes** [comment]
Still fails,
I just do everything the hard way...

**Comment by jwrhee** [comment]
I'm getting this issue as well. I've move the app into my applications folder and am trying to create a new project in an empty folder, but I'm still getting this message. The same thing happens when I try to open the example files.

**Comment by vlidholt** [comment]
What is your path to the project directory? Any strange characters in there or something along those lines.

**Comment by ezhes** [comment]
Application: /Applications
Project: ~/Documents

**Comment by vlidholt** [comment]
Thank you. Can you provide a pwd to the Documents directory, so that I can see the complete path? Also, have you copied the complete example project (including resource directories etc) to the Documents directory? Is the folder structure of the example intact?

**Comment by ezhes** [comment]
The full dictionary name is:
/Users/CC/Documents/
I can't provide the full PWD as I am traveling.
I tried the example file and it returns the same.

**Comment by therealhugocosta** [comment]
I had the same issue even after putting the project inside an empty directory.
I solved it by restarting CocosBuilder, just close it and open it again and create the new project inside an empty directory.

Bottom line is, if the error occurs it won't go away before you close and reopen CocosBuilder.

**Comment by vlidholt** [comment]
Which version of CocosBUilder are you using? This should have been fixed in RC4.

**Comment by therealhugocosta** [comment]
CocosBuilder 3 pre-alpha 1

**Comment by vlidholt** [comment]
Will release a new version in next week that includes the fix. If you need a newer version now, it's possible to get it from GitHub and build it yourself (master branch).
