### ISSUE TITLE
Default "Touch enabled" to true

### ISSUE THREAD

**Issue by kprichard-zynga** [cocos2d/CocosBuilder#46]
It is non-obvious to someone who has never used CocosBuilder that this box must be checked in order to received touch events in your code.

As a newbie cocos2d/CocosBuilder developer, this drove me crazy, wondering why my ccTouchesBegan/Ended implementations were not being invoked.

Please consider, at the very least as an enhancement.

**Comment by vlidholt** [comment]
Good point! Will fix!

**Comment by vlidholt** [comment]
Fixed

**Comment by kprichard-zynga** [comment]
Nice!  Thanks, Victor.  Maybe this will help others in the future.

On 7/19/12 1:43 PM, "Viktor Lidholt"
<reply+i-4827069-98be81107ca177e56865b8ef4ac53cdfdfd9ad30-751717@reply.gith
ub.com> wrote:
