### ISSUE TITLE
CCButton background sprite frame positioned incorrectly

### ISSUE THREAD

**Issue by tkowalski** [cocos2d/CocosBuilder#49]
Steps to reproduce:
Create a new project and:
1. Create a new CCLayer
2. Add a CCSprite
3. Add a CCButton and position you want
4. Choose  a background resource and set its width and height to exactly the size of the chosen image (absolutely).
5. save the project
6. open the project again and look at the layout again - the button background image is moved. 

If you modify the size slightly the background suddenly "jumps" to its correct position.

**Comment by khacanh** [comment]
I encountered this with 2.0rc0. 
If you set width and height different from the image size then it is positioned correctly.

**Comment by ealter** [comment]
That's what I did as a workaround

**Comment by himanshugupta53** [comment]
How about in the case of CCScrollView? Setting the width and height different from ccb file size doesn't help

**Comment by tkowalski** [comment]
What do you mean exactly ? I noticed this bug only on CCControlButton. Provide some example.

**Comment by himanshugupta53** [comment]
@tkowalski  Really!! Exactly what version are you using? I am using 2.0rc0
I saw this happening with CCScrollView, CCControlButton and CCBFile

**Comment by tkowalski** [comment]
My version:
CocosBuilder-2.0.0beta1.
I've got working CCScrollView this way, but sorry I forgot that I set up bigger content (height) than CCSprite inside:

mainScroll ccb:
- CCLayer (content size 1024x768)
  - CCScrollView (content size 1024x768 -> doesn't mean that it will be fullscreen, because it depends what will be sprite size) + container (scrollContent.ccb)

scrollContent:
- CCNode (content size 11800 x 768)
  - CCSprite smaller than 768

So it's working this way.

**Comment by himanshugupta53** [comment]
@tkowalski Tried what you mentioned. The issue is there, atleast in the 2.0rc2

Can you point me to the 2.0beta1 version? I'll give it a try.

**Comment by tkowalski** [comment]
@himanshugupta53
http://www.cocosbuilder.com/downloads/CocosBuilder-2.0.0beta1.zip

**Comment by himanshugupta53** [comment]
I tried with the beta version with no positive results. I am beginning to think that I might lack some understanding of how the objects are aligned. My scenario is as follows:

scrollContent.ccb:
CCNode (content size 8000_480, anchor point 0,0, position 0,0)
     - CCSprite (content size 800_479, anchor point 0,0, position 0,0)

scrollView.ccb:
CCLayer (content size 800_480, anchor point 0.5, 0.5, position 50%, 50%)
     - CCScrollView(content size 800_480, anchor point 0.5, 0.5, position 50%, 50%, content scrollContent.ccb)

What I see on the screen is (after scaling down a bit) - the image sprite is clipped to the top right quarter of the rectangle in ccscrollview. If I disable the "Clips to bounds" option, then I see the image in the whole rectangle. I don't understand why it is clipping to top right quarter. Not able to figure out, on what variables does the position of the sprite and the clipping depends upon.

**Comment by himanshugupta53** [comment]
I think I found the culprit. In the beforeDraw function in CCScrollView.m, following function call has been done to clip the content within its size.

glScissor(screenPos.x, screenPos.y, viewSize_.width_s, viewSize_.height_s);

It seems that screenPos is calculated by taking the world coordinates of the parent of the scroll view (and not the bottom left corner of the box), while viewSize is equivalent to the content size (and not the world coordinates of the top right corner of the box).

As a workaround, I am putting the position of the parent of the scrollview to (0,0), so that its world coordinated come out to (0,0)
