### ISSUE TITLE
Font support for CCLabelTTF

### ISSUE THREAD

**Issue by ghost** [cocos2d/CocosBuilder#5]
Right now, CCLabelTTF only supports 6 fonts. It would be nice to include a TTF file (or OTF), and within CocosBuilder be able to select and preview that font when creating a CCLabelTTF.

**Comment by vlidholt** [comment]
Agreed, this needs to be fixed. The problem is that those fonts were the only ones supported by the same name on iOS/Mac. I'll do some research into this issue!

**Comment by vlidholt** [comment]
Fixed
