### ISSUE TITLE
CCLabelBMFont doesn't behave properly when FNT file doesn't contains certain characters

### ISSUE THREAD

**Issue by MartinCote** [cocos2d/CocosBuilder#52]
If the FNT file doesn't contains all the characters from "Sample Text", CocosBuilder won't be able to render after changing the resolution.

Repro steps:
1. Create a FNT file with only a handful of characters (e.g., "Hello").
2. Use that FNT in CocosBuilder.
3. Change the resolution from iPhone <-> iPad. The "missing-font" font will be used.

After a quick investigation, I noticed that CocosBuilder tries to (temporarily) change the text to "Sample Text" when changing resolution.  Since the font doesn't have all the required characters, an exception is thrown and CocosBuilder then revers to the "missing-font" font.

**Comment by MartinCote** [comment]
Note that preventing Cocos2D to assert on invalid characters solves this issue:
//NSAssert(element, @"FontDefinition could not be found!");

**Comment by vlidholt** [comment]
This bug has been fixed in the cocos2d-iphone submodule
