### ISSUE TITLE
the latest cocosbuilder source code build error!

### ISSUE THREAD

**Issue by takehu** [cocos2d/CocosBuilder#55]
i check out the cocosbuilder's source code by github,and use the line command "git submodule init & git submodule update" check out the other modules.Then I build the source code by select the target of cocosbuilder,I get these error below:

cc1obj: error: unrecognized command line option "-Wno-sign-conversion"
cc1obj: error: unrecognized command line option "-fdiagnostics-print-source-range-info"
cc1obj: error: unrecognized command line option "-fdiagnostics-show-category=id"
cc1obj: error: unrecognized command line option "-fdiagnostics-parseable-fixits"
cc1obj: error: unrecognized command line option "-fobjc-arc"
Command /Developer/usr/bin/clang failed with exit code 1

with the target of "cocos2d iphone", my xcode is 4.2,the sdk is mac os 10.6,who can tell me what is the problem?thanks very much!

**Comment by vlidholt** [comment]
You will need to upgrade to the latest version of Xcode (4.3)

**Comment by takehu** [comment]
ok,I try it at once,thank you.
