### ISSUE TITLE
CCLabelBMFont + custom Anchor point

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/CocosBuilder#57]
CCLabelBMFont + custom Anchor point appears correctly on CCB, but not on device.

Probably CCB Reader is not setting the anchorPoint to the CCLabelBMFont.

Steps to reproduce it:
1. Create a CCLabelBMFont in CCB.
2. Set a custom Anchor Point
3. ( it will be displayed correctly on CCB )
4. Test it on the device... it won't use the new Anchor Point.

**Comment by vlidholt** [comment]
This works for me, unable to reproduce bug. Can you provide me with a test case?

**Comment by ricardoquesada** [comment]
Sure. Please download cocos2d "develop-v2" branch.
Open CocosBuilder and open the MainMenu.ccbproj located here:
~/cocos2d-iphone/Resources/Game/CCB

Open the "HUD.ccb" file.
You will see:
"SCORE    0        TIME 00.0"
Notice that the "0" is almost on the center of the screen.

If you run the game, you will notice it is not there.
To run the game open the "JS Watermelon" project and run in on the iPad or on Mac.

**Comment by vlidholt** [comment]
This bug has been fixed. It was most likely not an issue with the anchor points, but with the "nudge" function not updating object positions properly. Opening the ccb files and exporting them again should fix the issue.
