### ISSUE TITLE
Can't add iPad resolution to an existing project

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/CocosBuilder#58]
Problem:
I create an iPhone only game... (or simple I forget to also add the iPad resolution option too).
Once the "File" is created I can't add an iPad resolution to it.
Adding a custom resolution is not the same because it won't load the "-ipad" resources.

The only way to see it on iPad is to restart the project from scratch (... or edit manually the .ccb file )

**Comment by vlidholt** [comment]
To add an iPad resolution:
1. Select View > Edit Resolutions...
2. Click the + button
3. Name the new resolution "iPad Landscape" set width to 1024, height to 768 and resource extension to "ipad" or "ipad hd" (it's a drop down menu). Set the scale to 2.00

**Comment by ricardoquesada** [comment]
I didn't know how to change the scale...
Perhaps it would be easier to have an already predefined options for the iPad, like when you create the "file".

**Comment by vlidholt** [comment]
Yes, a function like that would be good! I am adding a new issue for this.
