### ISSUE TITLE
Can't change color of a CCLabelBMFont (possible others too)

### ISSUE THREAD

**Issue by ricardoquesada** [cocos2d/CocosBuilder#59]
Steps to reproduce it:
1. create a CCLabelBMFont in CCB
2. click on the color
3. The "Colors" dialog will appear
4. Click on the 2nd tab (the sliders)
5. Select the Gray Scale Slider
6. Select a color

You will notice that the color is updated on the CCB options, but not on the label.

**Comment by vlidholt** [comment]
Fixed (on branch v2)
