### ISSUE TITLE
Cannot add CCMenu

### ISSUE THREAD

**Issue by tthmok** [cocos2d/CocosBuilder#6]
Latest commit cannot add CCMenu, nothing appears in Structure or in the scene.  Loading of the example.ccb provided in CocosBuilder shows no brown button for Press Me! where there used to be.

**Comment by tthmok** [comment]
Strange happenings, seems to be inconsistent for me, I'll leave it closed until I can reproduce easily.

**Comment by vlidholt** [comment]
If it happens again, can you check the Console.app for any output there? Thanks!
