### ISSUE TITLE
Can't add children to CCMenuItemSprite

### ISSUE THREAD

**Issue by frozax** [cocos2d/CocosBuilder#68]
We can't add children to a CCMenuItemSprite, while cocos2d supports it. I tested to add children (such as a CCLabelBMFont) to a CCMenuItemSprite in code and it worked properly (using cocos2dx).

**Comment by vlidholt** [comment]
This is currently not supported in CocosBuilder

**Comment by Fexxel** [comment]
Are you planing on supporting this soon? I really need this as well.

**Comment by vlidholt** [comment]
The way that CCMenuItemImage is made (it uses childs for it's different states) makes it very hard to support this feature in CocosBuilder. I suggest that you use either CCControlButton if you need a label on your button. Or place the label on top of the CCMenuItemImage (if you need to move them together you can place the item and the label in a node).
