### ISSUE TITLE
CCBI has misplaced nodes at runtime, CocosBuilder shows them correctly placed.

### ISSUE THREAD

**Issue by ghost** [cocos2d/CocosBuilder#69]
While creating a multi-resolution project in CocosBuilder i used both, iPhone and iPad resolutions, i aligned everything the way i wanted using percentages, in the preview offered by CocosBuilder i saw everything correctly. When i used the generated CCBI in Cocos2D and run my application for the iPad i got everything misplaced like if the position of every node in the interface had been moved by a certain amount of pixels.

**Comment by vlidholt** [comment]
Which version of CocosBuilder are you using? I know that CocosBuilder 3 pre alpha had this problem (it's fixed in pre alpha 1) if it's the same bug.
