### ISSUE TITLE
CCMenuItemImage Block empty causes crash

### ISSUE THREAD

**Issue by tthmok** [cocos2d/CocosBuilder#7]
Steps to reproduce:
1. Create new ccb
2. Add CCMenu
3. Add CCMenuItemImage into CCMenu
4. Save and quit
5. Load the created ccb

Causes crash on line 232 of CCBreaderInternal.m in an attempt to do objectAtIndex of empty serializedValue.

**Comment by vlidholt** [comment]
Fixed (on master branch)
