### ISSUE TITLE
Custom resolutions are ignored in CCBReader

### ISSUE THREAD

**Issue by MartinCote** [cocos2d/CocosBuilder#71]
I have some ccb files with custom resolutions (say, 320x45 on iPhone, 768x90 on iPad).  However, those resolutions don't seem to be exported in the ccbi file, nor read by CCBReader (which always take the full iPhone/iPad resolution).

**Comment by vlidholt** [comment]
This currently works as intended. If you need to load a ccb-file to a specific resolution you should use the:
- (CCNode_) nodeGraphFromFile:(NSString_) file owner:(id)owner parentSize:(CGSize)parentSize
  and pass the size that you want to load the file through the parentSize parameter

**Comment by MartinCote** [comment]
Ok. I was hoping that it could automatically use the size I provide in the ccb-file.  Now I have to manually keep both the ccb-file root size and the size I pass to parentSize in sync.

If this works as intended, please disregard the pull request.

**Comment by vlidholt** [comment]
The approach you are suggesting would work on iOS where there are different resolutions for iPhone and iPad only. But it would not be viable for Android devices which has a very large variety of resolutions.

**Comment by MartinCote** [comment]
True. Thanks for the clarification.
