### ISSUE TITLE
Double-clicking ccbproj file launches CocosBuilder but doesn't open project

### ISSUE THREAD

**Issue by samkass** [cocos2d/CocosBuilder#73]
1. In Examples sub-folder, find CocosBuilderExample.ccbproj
2. Double-click it
3. CocosBuilder opens

Expected:
4. Should open project file

Observed:
4. Empty project opens

The workaround is easy (choose open from within the app), but as this is the very first impression a typical user might have of CocosBuilder it probably is more important than a typical UI glitch.

**Comment by vlidholt** [comment]
This is fixed in version 2.1 beta
