### ISSUE TITLE
Changing Position to Percentage Bug

### ISSUE THREAD

**Issue by therealhugocosta** [cocos2d/CocosBuilder#74]
Hi,

Using the CocosBuilder pre-alpha 1.
1. Create a new project with multi resolution (iphone and ipad landscape)
2. Add a new ccbi as cclayer
3. Drag new image to the stage and a new ccsprite is added
4. Click on the % on the ccnode position

The ccprite will be centered on the bottom left corner of the stage and it's impossible to move it, only by changing back to normal positioning.

**Comment by vlidholt** [comment]
You will need to set the parents (root object) layer's content size to 100% x 100%. In latest version on GitHub this is the default when creating new ccb-files.
