### ISSUE TITLE
Setting timelines for CCBFile-node doesn't have any effect on the simulator

### ISSUE THREAD

**Issue by wasedaigo** [cocos2d/CocosBuilder#86]
In CocosBuilder Version 2.1 alpha, importing CCBFile-node and setting up timelines works properly on the editor (I tried with position & scale) . However when I load the data and play it with cocos2d on iOSSimulator, it seems like CCBFile-node timeline has no effect.

It is possible to workaround by adding an extra parent node to the CCBFile-node and controlling it instead.  However it is better to see editor&player behave the same.

**Comment by vlidholt** [comment]
Thanks, I will have a look at this!

**Comment by vlidholt** [comment]
Fixed
