### ISSUE TITLE
Crash when publishing scene with sprite frame

### ISSUE THREAD

**Issue by ghost** [cocos2d/CocosBuilder#96]
Hello,

I just found that Cocos consistently crashes when i want to publish a scene which works with sprite frames.

How to reproduce:
(1) Create an i pad scene with CALayer as root element
(2) Add an arbitrary image 1.png as sprite
(3) Set two "keyframes" for the "spriteframe", the first with 1.png, the second with 2.png
(4) Save the project
(5) Publish the project
-> Crash.

I can reproduce with any png or jpeg file, small or large.

I hope it's not about the way I set the keyframes, though, but i couldn't find a different way to do it.

Edit: I can reproduce with latest version of 2.1 (beta0) and 3.0 prealpha.

**Comment by airlst** [comment]
This is the log message
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ccbi export: Trying to write string not added to cache (1.jpg)'

**Comment by vlidholt** [comment]
Fixed! Will release a new beta in the next few days!

**Comment by airlst** [comment]
Awesome, thanks!
