### ISSUE TITLE
Building CocosPlayer for CocosBuilder 2.1 Beta

### ISSUE THREAD

**Issue by Tw0bit** [cocos2d/CocosBuilder#97]
I am trying to build the CocosPlayer to use with the JavaScript feature of CocosBuilder 2.1 beta.

When I try to build CocosPlayer (xCode 4.4.1 and 4.5 GM on Mountain Lion and Lion) using the iOS 5.0 SDK:

Ld /Users/twobit/Library/Developer/Xcode/DerivedData/CocosPlayer-dhoxbgfrsdnhpmgxxvwehlsppvhs/Build/Products/Debug-iphoneos/CocosPlayer.app/CocosPlayer normal armv7
    cd /Users/twobit/Desktop/CocosBuilder/CocosPlayer
    setenv IPHONEOS_DEPLOYMENT_TARGET 4.0
    setenv PATH "/Applications/Xcode44-iOS5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode44-iOS5.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode44-iOS5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -L/Users/twobit/Library/Developer/Xcode/DerivedData/CocosPlayer-dhoxbgfrsdnhpmgxxvwehlsppvhs/Build/Products/Debug-iphoneos -L/Users/twobit/Desktop/CocosBuilder/CocosPlayer/external/spidermonkey/iOS/lib -L/Users/twobit/Desktop/CocosBuilder/CocosPlayer/external -L/Users/twobit/Desktop/CocosBuilder/CocosPlayer/external/spidermonkey/mac/lib -F/Users/twobit/Library/Developer/Xcode/DerivedData/CocosPlayer-dhoxbgfrsdnhpmgxxvwehlsppvhs/Build/Products/Debug-iphoneos -filelist /Users/twobit/Library/Developer/Xcode/DerivedData/CocosPlayer-dhoxbgfrsdnhpmgxxvwehlsppvhs/Build/Intermediates/CocosPlayer.build/Debug-iphoneos/CocosPlayer.build/Objects-normal/armv7/CocosPlayer.LinkFileList -dead_strip -ObjC -fobjc-link-runtime -miphoneos-version-min=4.0 -lSSZipArchive -lCocosDenshion -lChipmunk -framework Foundation -framework UIKit -framework CoreGraphics -framework OpenGLES -framework QuartzCore -lcocos2d -lz -framework OpenAL -framework AudioToolbox -framework AVFoundation -ljs_static -o /Users/twobit/Library/Developer/Xcode/DerivedData/CocosPlayer-dhoxbgfrsdnhpmgxxvwehlsppvhs/Build/Products/Debug-iphoneos/CocosPlayer.app/CocosPlayer

All the modules/dependencies build without an issue (i had to fix linkages to CCBActionManager.h/.m in the CocosBuilderExample folder.

Any Ideas? I can confirm this file exists: /Users/twobit/Library/Developer/Xcode/DerivedData/CocosPlayer-dhoxbgfrsdnhpmgxxvwehlsppvhs/Build/Products/Debug-iphoneos/CocosPlayer.app

CocosBuilder compiles without any issues.

**Comment by vlidholt** [comment]
CocosPlayer is still in a very experimental. It is planned on being completed for CocosBuilder 3 (which will likely be the release after 2.1). That is why it is currently not up to date.

**Comment by Tw0bit** [comment]
Hi vlidholt,

Thanks for the information :-) looking forward to V3.

Tw0bit.
